"""Engine-independent public runtime identity schemas."""

from pathlib import PurePosixPath

from tools.maintenance.dto_schema.model import DtoSchema


# Public .inc files are compiled by MSVC on hosts whose active code page cannot
# represent the generator's historical em dash. Keep this generated banner
# ASCII so consuming the engine-independent header produces no C4819 warning.
ASCII_FILE_HEADER = (
  "// GENERATED by tools/maintenance/dto_schema - edit the schema, not this file.\n\n"
)

PUBLIC_RUNTIME_CONTRACT_CPP_TYPES = frozenset(
  {
    "std::uint64_t",
    "RuntimeIdentity128",
    "RuntimeHostIdentity",
    "RuntimeIncarnationRef",
    "RuntimeWorldRef",
    "RuntimeEpisodeRef",
    "RuntimeRequestRef",
  }
)


def validate_public_runtime_contract_schema(schema: DtoSchema) -> DtoSchema:
  """Fail closed when a public identity field gains an unapproved C++ type."""

  output_path = PurePosixPath(schema.output_path)
  expected_parent = PurePosixPath(
    "include/echelon_forge/runtime_contracts/detail"
  )
  if output_path.parent != expected_parent:
    raise ValueError(
      f"public runtime contract {schema.name} has invalid output path: "
      f"{schema.output_path}"
    )
  if schema.file_header != ASCII_FILE_HEADER:
    raise ValueError(
      f"public runtime contract {schema.name} must use the closed ASCII header"
    )

  field_groups = frozenset(field.group for field in schema.fields)
  if len(field_groups) != 1:
    raise ValueError(
      f"public runtime contract {schema.name} must use exactly one field macro"
    )
  field_group = next(iter(field_groups))
  if not field_group.startswith("EF_RUNTIME_") or not field_group.endswith("_FIELD"):
    raise ValueError(
      f"public runtime contract {schema.name} has invalid field macro: {field_group}"
    )
  if schema.file_footer != f"\n#undef {field_group}\n":
    raise ValueError(
      f"public runtime contract {schema.name} has an open or mismatched footer"
    )

  forbidden_fields = tuple(
    f"{field.name}:{field.cpp_type}"
    for field in schema.fields
    if field.cpp_type not in PUBLIC_RUNTIME_CONTRACT_CPP_TYPES
  )
  if forbidden_fields:
    raise ValueError(
      f"public runtime contract {schema.name} has forbidden field types: "
      f"{forbidden_fields}"
    )
  return schema
