from __future__ import annotations

import re
from pathlib import Path
import subprocess

from tools.maintenance.dto_schema.generate import load_schemas
from tools.maintenance.dto_schema.model import DtoSchema, Field
from tools.maintenance.dto_schema.schemas.runtime_contracts import (
  ASCII_FILE_HEADER,
  PUBLIC_RUNTIME_CONTRACT_CPP_TYPES,
  validate_public_runtime_contract_schema,
)


REPO_ROOT = Path(__file__).resolve().parents[3]
PUBLIC_HEADER = (
  REPO_ROOT
  / "include"
  / "echelon_forge"
  / "runtime_contracts"
  / "runtime_identity.h"
)
CMAKE = REPO_ROOT / "CMakeLists.txt"
COMPILE_TEST = REPO_ROOT / "src" / "tests" / "test_runtime_identity_contracts.cpp"
PUBLIC_SCHEMA_PREFIX = "include/echelon_forge/runtime_contracts/detail/"


def _text(path: Path) -> str:
  return path.read_text(encoding="utf-8")


def _public_identity_schemas():
  return tuple(
    schema
    for _, schema in load_schemas()
    if schema.output_path.startswith(PUBLIC_SCHEMA_PREFIX)
  )


def test_public_identity_header_is_versioned_and_engine_independent() -> None:
  header = _text(PUBLIC_HEADER)
  includes = re.findall(r'^\s*#\s*include\s+([<"][^>"]+[>"])', header, re.MULTILINE)
  standard_includes = {value for value in includes if value.startswith("<c") or value == "<type_traits>"}
  generated_includes = {
    f"<{schema.output_path.removeprefix('include/')}>"
    for schema in _public_identity_schemas()
  }

  assert standard_includes == {"<cstddef>", "<cstdint>", "<type_traits>"}
  assert generated_includes == set(includes) - standard_includes
  assert "namespace echelon_forge::runtime_contracts::v1" in header
  assert "kRuntimeIdentityContractGeneration = 1" in header

  for forbidden in (
    "components/",
    "core/",
    "runtime/facade/",
    "flecs",
    "nlohmann",
    "nanobind",
    "std::string",
    "std::vector",
    "void *",
  ):
    assert forbidden not in header


def test_registered_schema_is_the_single_public_field_list_owner() -> None:
  header = _text(PUBLIC_HEADER)
  schemas = _public_identity_schemas()
  schema_names = {schema.name for schema in schemas}

  assert schema_names == {
    "runtime_identity_128",
    "runtime_host_identity",
    "runtime_incarnation_ref",
    "runtime_world_ref",
    "runtime_entity_ref",
    "runtime_episode_ref",
    "runtime_request_ref",
    "runtime_result_ref",
  }
  for schema in schemas:
    generated_path = REPO_ROOT / schema.output_path
    assert generated_path.is_file()
    assert "GENERATED by tools/maintenance/dto_schema" in _text(generated_path)
    assert f"<{schema.output_path.removeprefix('include/')}>" in header

  result_schema = next(schema for schema in schemas if schema.name == "runtime_result_ref")
  assert tuple(field.name for field in result_schema.fields) == ("request",)
  assert all(field.name != "result_sequence" for schema in schemas for field in schema.fields)


def test_public_schema_type_allowlist_rejects_raw_pointer_injection() -> None:
  for schema in _public_identity_schemas():
    assert all(
      field.cpp_type in PUBLIC_RUNTIME_CONTRACT_CPP_TYPES
      for field in schema.fields
    )

  malicious = DtoSchema(
    name="malicious_public_pointer",
    output_path="include/echelon_forge/runtime_contracts/detail/malicious.inc",
    fields=(
      Field("engine_address", "void *", "{}", "EF_RUNTIME_MALICIOUS_FIELD"),
    ),
    file_header=ASCII_FILE_HEADER,
    file_footer="\n#undef EF_RUNTIME_MALICIOUS_FIELD\n",
  )
  try:
    validate_public_runtime_contract_schema(malicious)
  except ValueError as exc:
    assert "engine_address:void *" in str(exc)
  else:
    raise AssertionError("public runtime contract accepted a raw pointer field")

  include_injection = DtoSchema(
    name="malicious_public_include",
    output_path="include/echelon_forge/runtime_contracts/detail/malicious.inc",
    fields=(
      Field("identity", "std::uint64_t", "0", "EF_RUNTIME_MALICIOUS_FIELD"),
    ),
    file_header=(
      ASCII_FILE_HEADER
      + '#include "../../../../src/runtime/contracts/world_batch_contracts.h"\n'
    ),
    file_footer="\n#undef EF_RUNTIME_MALICIOUS_FIELD\n",
  )
  try:
    validate_public_runtime_contract_schema(include_injection)
  except ValueError as exc:
    assert "closed ASCII header" in str(exc)
  else:
    raise AssertionError("public runtime contract accepted an include injection")


def test_public_refs_separate_stable_host_from_published_incarnation() -> None:
  header = _text(PUBLIC_HEADER)

  for public_type in (
    "RuntimeIdentity128",
    "RuntimeHostIdentity",
    "RuntimeIncarnationRef",
    "RuntimeWorldRef",
    "RuntimeEntityRef",
    "RuntimeEpisodeRef",
    "RuntimeRequestRef",
    "RuntimeResultRef",
  ):
    assert f"struct {public_type}" in header
    assert f"EF_ASSERT_PUBLIC_VALUE_CONTRACT({public_type})" in header

  assert "same_runtime_host" in header
  assert "same_runtime_incarnation" in header
  assert "well_formed()" in header
  assert ".valid()" not in header
  assert "P4 must validate" in header
  assert "raw-memory persistence, hashing, signing, or IPC encoding is forbidden" in header
  assert "P3-B\n// must provide the only canonical JSON projection" in header
  assert "do not qualify any Windows/Linux release row" in header


def test_cmake_uses_generated_target_properties_and_final_graph_gate() -> None:
  cmake = _text(CMAKE)

  assert "set(EF_RUNTIME_CONTRACTS_SOURCES" in cmake
  assert "add_library(ef_runtime_contracts STATIC ${EF_RUNTIME_CONTRACTS_SOURCES})" in cmake
  assert "add_library(EchelonForge::runtime_contracts ALIAS ef_runtime_contracts)" in cmake
  assert "ef_runtime_contracts_boundary_manifest.txt" in cmake
  assert "$<TARGET_PROPERTY:ef_runtime_contracts,LINK_LIBRARIES>" in cmake
  assert "$<TARGET_PROPERTY:ef_runtime_contracts,INTERFACE_LINK_LIBRARIES>" in cmake
  assert "runtime_contracts_boundary" in cmake
  assert "verify_runtime_contracts_boundary.cmake" in cmake

  gate_call = "ef_assert_p3a_runtime_contract_boundary()"
  assert cmake.rstrip().endswith(gate_call)
  assert "ef_collect_directory_targets" in cmake
  assert 'PROPERTY SUBDIRECTORIES' in cmake
  assert "allowed_host_consumers ef_runtime_host_candidate_test" in cmake
  assert "allowed_consumers ef_runtime_contracts_compile_test" in cmake
  assert "P4-A/P4-B replace" in cmake
  assert "P5-D cutover" in cmake


def test_generated_boundary_verifier_rejects_link_include_source_and_install_drift(
  tmp_path: Path,
) -> None:
  verifier = REPO_ROOT / "cmake" / "verify_runtime_contracts_boundary.cmake"
  expected_include = (tmp_path / "include").as_posix()
  clean_manifest = (
    "type=STATIC_LIBRARY\n"
    "links=\n"
    "interface_links=\n"
    f"includes={expected_include}\n"
    f"interface_includes={expected_include}\n"
    "sources=include/runtime_identity.h|src/runtime_identity.cpp\n"
  )

  cases = {
    "direct_link": (clean_manifest.replace("links=\n", "links=ef_core\n"), "# clean\n"),
    "interface_include": (
      clean_manifest.replace(
        f"interface_includes={expected_include}",
        "interface_includes=D:/private/src",
      ),
      "# clean\n",
    ),
    "source_graph": (
      clean_manifest.replace(
        "sources=include/runtime_identity.h|src/runtime_identity.cpp",
        "sources=src/runtime_identity.cpp|src/ef_facade_adapter.cpp",
      ),
      "# clean\n",
    ),
    "install_graph": (clean_manifest, "# install ef_runtime_contracts\n"),
  }
  for case_name, (manifest_text, install_text) in cases.items():
    manifest = tmp_path / f"{case_name}.manifest.txt"
    install_script = tmp_path / f"{case_name}.install.cmake"
    manifest.write_text(manifest_text, encoding="utf-8")
    install_script.write_text(install_text, encoding="utf-8")
    result = subprocess.run(
      [
        "cmake",
        f"-DMANIFEST={manifest}",
        f"-DINSTALL_SCRIPT={install_script}",
        f"-DEXPECTED_INCLUDE_ROOT={expected_include}",
        "-P",
        str(verifier),
      ],
      cwd=REPO_ROOT,
      check=False,
      capture_output=True,
      text=True,
    )
    assert result.returncode != 0, f"{case_name} drift was accepted"


def test_focused_native_consumer_and_production_graph_remain_separate() -> None:
  cmake = _text(CMAKE)
  source = _text(COMPILE_TEST)

  assert source.startswith("#include <echelon_forge/runtime_contracts/runtime_identity.h>")
  assert "runtime_contracts::v1" in source
  for forbidden in ('"core/', '"components/', '"runtime/facade/'):
    assert forbidden not in source

  target = cmake.split("add_executable(ef_runtime_contracts_compile_test", 1)[1].split(
    ")", 1
  )[0]
  link = cmake.split("target_link_libraries(ef_runtime_contracts_compile_test", 1)[1].split(
    ")", 1
  )[0]
  assert "test_runtime_identity_contracts.cpp" in target
  assert "ef_runtime_contracts" in link
  for forbidden in ("ef_core", "ef_facade", "ef_composition", "flecs", "doctest"):
    assert forbidden not in target
    assert forbidden not in link

  allowed_source_consumers = {
    REPO_ROOT / "src" / "runtime" / "contracts" / "public" / "runtime_identity.cpp",
    REPO_ROOT / "src" / "runtime" / "host" / "runtime_host_candidate.h",
    REPO_ROOT / "src" / "runtime" / "host" / "runtime_state_transfer_candidate.h",
    COMPILE_TEST,
  }
  source_consumers = {
    path
    for path in (REPO_ROOT / "src").rglob("*")
    if path.suffix in {".h", ".hpp", ".cpp", ".cc"}
    and "echelon_forge/runtime_contracts/runtime_identity.h" in _text(path)
  }
  assert source_consumers == allowed_source_consumers


def test_p3a_does_not_cut_over_legacy_world_refs_or_facade_types() -> None:
  legacy_world_contracts = _text(
    REPO_ROOT / "src" / "runtime" / "contracts" / "world_batch_contracts.h"
  )
  facade_types = _text(REPO_ROOT / "src" / "runtime" / "facade" / "runtime_facade_types.h")

  assert "echelon_forge/runtime_contracts/runtime_identity.h" not in legacy_world_contracts
  assert "RuntimeHostIdentity" not in facade_types
  assert "RuntimeIncarnationRef" not in facade_types
  assert "RuntimeEntityRef" not in facade_types
