"""Declarative DTO schema parsed from src/runtime/contracts/detail/damage/effects_event_fields.inc."""

from __future__ import annotations

from tools.maintenance.dto_schema.model import DtoSchema, Field


FILE_HEADER = (
  '// Private X-macro fragment: single owner of the EffectsEvent field surface.\n'
  '// Consumers must define both macros before including this file and #undef\n'
  '// them afterwards:\n'
  '//   EF_EFFECTS_EVENT_FIELD(type, name, default_value)\n'
  '//     field owned by EffectsEvent only.\n'
  '//   EF_EFFECTS_EVENT_RESULT_FIELD(type, name, default_value)\n'
  '//     field that also exists on EffectsResult under the same member name and\n'
  '//     is projected by engagement_events::apply_effects_result_fields.\n'
  '// Field order is the authoritative EffectsEvent declaration order; designated\n'
  '// initializers and the Python binding surface depend on it, so do not reorder.\n'
  '// Intentionally no include guard: the list is re-expanded under different\n'
  '// macro definitions (contract struct, result projection, Python bindings).\n'
  '\n'
  '#if !defined(EF_EFFECTS_EVENT_FIELD) || !defined(EF_EFFECTS_EVENT_RESULT_FIELD)\n'
  '#error "define EF_EFFECTS_EVENT_FIELD and EF_EFFECTS_EVENT_RESULT_FIELD before including effects_event_fields.inc"\n'
  '#endif\n'
  '\n'
)
FILE_FOOTER = ""


SCHEMA = DtoSchema(
  name='effects_event_fields',
  output_path='src/runtime/contracts/detail/damage/effects_event_fields.inc',
  file_header=FILE_HEADER,
  fields=(
    Field(name='event_id', cpp_type='std::uint64_t', default='0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='munition', cpp_type='EngagementEntityRef', default='{}', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='target', cpp_type='EngagementEntityRef', default='{}', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='trigger_type', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='outcome_state', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_time_s', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='nearest_approach_time_s', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='miss_distance_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_local_forward_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_local_right_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_local_up_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_heading_deg', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_pitch_deg', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_roll_deg', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='closure_mps', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='missile_axis_forward', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='missile_axis_right', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='missile_axis_up', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='quality', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='confidence', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='effect_family', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='warhead_mass_kg', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='warhead_lethal_radius_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='warhead_profile_synthetic', cpp_type='bool', default='true', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='damage_scalar_synthetic', cpp_type='bool', default='true', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_type', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_trigger_radius_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_delay_s', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_reliability', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_profile_synthetic', cpp_type='bool', default='true', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_signature_source', cpp_type='std::string', default='"none"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_target_signature', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_signature_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_effective_reliability', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_contact_surface_distance_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_contact_penetration_depth_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_contact_surface_tolerance_m', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_contact_inside_hitbox', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_sensor_opportunity_source', cpp_type='std::string', default='"none"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_sensor_opportunity_score', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_terminal_track_valid', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_target_detected', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_target_detection_source', cpp_type='std::string', default='"none"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_target_detection_confidence', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_target_detection_threshold', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='detonation_point_source', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='fuze_mechanism_coverage_score', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_FIELD'),
    Field(name='direct_hitbox_intersection', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='projected_hitbox_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='spatial_effect_scale', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_armor_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_exposure_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_effect_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_fragment_energy_j', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_fragment_areal_density_per_m2', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_penetration_margin', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_blast_overpressure_kpa', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_blast_impulse_kpa_ms', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_blast_scaled_distance_m_kg13', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_rod_cut_margin', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='mechanism_surface_incidence_cos', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_spatial_sample_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_spatial_hit_estimate', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_spatial_hit_fraction', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_spatial_energy_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_spatial_pattern_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_orientation_axis_forward', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_orientation_axis_right', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_orientation_axis_up', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='warhead_orientation_pattern_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_threshold_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_source', cpp_type='std::string', default='"none"', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_calibrated', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_evidence_dataset_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_evidence_row_id', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_evidence_source_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_probability_evidence_provenance', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_sample', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_failure_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_hit_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_mechanism_load_rows', cpp_type='std::vector<ComponentMechanismLoadRow>', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_response_rows', cpp_type='std::vector<ComponentResponseRow>', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_name', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_system', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_redundancy_group', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_critical', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_redundancy_group_id', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_integrity', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_fragment_energy_j', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_fragment_areal_density_per_m2', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_penetration_margin', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_blast_overpressure_kpa', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_blast_impulse_kpa_ms', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_blast_scaled_distance_m_kg13', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_rod_cut_margin', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_primary_mechanism_surface_incidence_cos', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_redundancy_group_availability', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_redundancy_group_member_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='component_redundancy_group_failed_count', cpp_type='std::uint32_t', default='0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_profile_present', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_profile_synthetic', cpp_type='bool', default='true', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_calibrated_evidence', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_pk_authority', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_deterministic_fuze_authority', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_dataset_valid', cpp_type='bool', default='false', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_dataset_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_calibration_status', cpp_type='std::string', default='"none"', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_provenance', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_schema_version', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_source_kind', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_source_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_artifact_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_manifest_schema_version', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_status', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_artifact_sha256', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validated_surrogate_model_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_benchmark_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_metrics_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_evidence_validation_acceptance_criteria_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_aspect_bucket', cpp_type='std::string', default='"unknown"', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_family_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_aspect_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_closure_mps', cpp_type='double', default='0.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_closure_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_miss_distance_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_effect_scale', cpp_type='double', default='1.0', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_effect_scale_source', cpp_type='std::string', default='"profile_scale"', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_effect_scale_evidence_row_id', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_effect_scale_evidence_source_ref', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_effect_scale_evidence_provenance', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='air_system_hit_flags', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='air_system_spatial_scales', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='vulnerability_scale_trace', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_RESULT_FIELD'),
    Field(name='producer_node_id', cpp_type='std::string', default='{}', group='EF_EFFECTS_EVENT_FIELD'),
  ),
  file_footer=FILE_FOOTER,
)
