"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'ils_valid', 'ils_loc_dev', 'ils_gs_dev', 'ils_dme_m', 'has_prev_loc', 'prev_loc_abs', 'has_prev_gs', 'prev_gs_abs', 'has_prev_dme', 'prev_dme_m', 'localizer_weight', 'localizer_deadband', 'localizer_norm', 'localizer_power', 'localizer_clip', 'localizer_improve_weight', 'glideslope_weight', 'glideslope_deadband', 'glideslope_norm', 'glideslope_power', 'glideslope_clip', 'glideslope_improve_weight', 'dme_progress_weight', 'dme_progress_localizer_band', 'dme_progress_glideslope_band', 'dme_progress_quality_power', 'capture_bonus', 'capture_localizer_band', 'capture_glideslope_band', 'sink_rate_weight', 'flare_agl_m', 'curr_alt_agl_m', 'sink_rate_mps', 'sink_rate_deadband_mps', 'sink_rate_norm_mps', 'sink_rate_power', 'sink_rate_clip')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('valid', 'ils_valid', 'ils_loc_dev', 'ils_gs_dev', 'ils_dme_m', 'has_prev_loc', 'prev_loc_abs', 'has_prev_gs', 'prev_gs_abs', 'has_prev_dme', 'prev_dme_m', 'localizer_weight', 'localizer_deadband', 'localizer_norm', 'localizer_power', 'localizer_clip', 'localizer_improve_weight', 'glideslope_weight', 'glideslope_deadband', 'glideslope_norm', 'glideslope_power', 'glideslope_clip', 'glideslope_improve_weight', 'dme_progress_weight', 'dme_progress_localizer_band', 'dme_progress_glideslope_band', 'dme_progress_quality_power', 'capture_bonus', 'capture_localizer_band', 'capture_glideslope_band', 'sink_rate_weight', 'flare_agl_m', 'curr_alt_agl_m', 'sink_rate_mps', 'sink_rate_deadband_mps', 'sink_rate_norm_mps', 'sink_rate_power', 'sink_rate_clip')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'ils_valid': ('bool', 'False'),
    'ils_loc_dev': ('float', '0.0'),
    'ils_gs_dev': ('float', '0.0'),
    'ils_dme_m': ('float', '0.0'),
    'has_prev_loc': ('bool', 'False'),
    'prev_loc_abs': ('float', '0.0'),
    'has_prev_gs': ('bool', 'False'),
    'prev_gs_abs': ('float', '0.0'),
    'has_prev_dme': ('bool', 'False'),
    'prev_dme_m': ('float', '0.0'),
    'localizer_weight': ('float', '0.0'),
    'localizer_deadband': ('float', '0.0'),
    'localizer_norm': ('float', '1.0'),
    'localizer_power': ('float', '2.0'),
    'localizer_clip': ('float', '0.0'),
    'localizer_improve_weight': ('float', '0.0'),
    'glideslope_weight': ('float', '0.0'),
    'glideslope_deadband': ('float', '0.0'),
    'glideslope_norm': ('float', '1.0'),
    'glideslope_power': ('float', '2.0'),
    'glideslope_clip': ('float', '0.0'),
    'glideslope_improve_weight': ('float', '0.0'),
    'dme_progress_weight': ('float', '0.0'),
    'dme_progress_localizer_band': ('float', '0.0'),
    'dme_progress_glideslope_band': ('float', '0.0'),
    'dme_progress_quality_power': ('float', '1.0'),
    'capture_bonus': ('float', '0.0'),
    'capture_localizer_band': ('float', '0.20'),
    'capture_glideslope_band': ('float', '0.20'),
    'sink_rate_weight': ('float', '0.0'),
    'flare_agl_m': ('float', '20.0'),
    'curr_alt_agl_m': ('float', '0.0'),
    'sink_rate_mps': ('float', '0.0'),
    'sink_rate_deadband_mps': ('float', '0.0'),
    'sink_rate_norm_mps': ('float', '2.0'),
    'sink_rate_power': ('float', '2.0'),
    'sink_rate_clip': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
