"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'approach_localizer', 'approach_localizer_improve', 'approach_glideslope', 'approach_glideslope_improve', 'approach_dme_progress', 'approach_capture_bonus', 'landing_sink_rate_penalty', 'clear_history', 'next_prev_valid', 'next_prev_loc_abs', 'next_prev_gs_abs', 'next_prev_dme_m')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'approach_localizer', 'approach_localizer_improve', 'approach_glideslope', 'approach_glideslope_improve', 'approach_dme_progress', 'approach_capture_bonus', 'landing_sink_rate_penalty', 'clear_history', 'next_prev_valid', 'next_prev_loc_abs', 'next_prev_gs_abs', 'next_prev_dme_m'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'approach_localizer': ('float', '0.0'),
    'approach_localizer_improve': ('float', '0.0'),
    'approach_glideslope': ('float', '0.0'),
    'approach_glideslope_improve': ('float', '0.0'),
    'approach_dme_progress': ('float', '0.0'),
    'approach_capture_bonus': ('float', '0.0'),
    'landing_sink_rate_penalty': ('float', '0.0'),
    'clear_history': ('bool', 'False'),
    'next_prev_valid': ('bool', 'False'),
    'next_prev_loc_abs': ('float', '0.0'),
    'next_prev_gs_abs': ('float', '0.0'),
    'next_prev_dme_m': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
