"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('header', 'component_name', 'component_system', 'component_redundancy_group_id', 'direct_hit', 'distance_m', 'effect_scale', 'spatial_intersection_fraction', 'pattern_weight', 'orientation_weight', 'receiver_exposure_fraction', 'armor_transmission', 'sampling_confidence', 'load_intensity_scale', 'fragment_energy_j', 'fragment_density_per_m2', 'penetration_margin', 'blast_overpressure_kpa', 'blast_impulse_kpa_ms', 'blast_scaled_distance_m_kg13', 'rod_cut_margin', 'surface_incidence_cos', 'load_source')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('header', 'component_name', 'component_system', 'component_redundancy_group_id', 'direct_hit', 'distance_m', 'effect_scale', 'spatial_intersection_fraction', 'pattern_weight', 'orientation_weight', 'receiver_exposure_fraction', 'armor_transmission', 'sampling_confidence', 'load_intensity_scale', 'fragment_energy_j', 'fragment_density_per_m2', 'penetration_margin', 'blast_overpressure_kpa', 'blast_impulse_kpa_ms', 'blast_scaled_distance_m_kg13', 'rod_cut_margin', 'surface_incidence_cos', 'load_source')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'header': ('object', "'{}'"),
    'component_name': ('str', "'{}'"),
    'component_system': ('str', "'{}'"),
    'component_redundancy_group_id': ('str', "'{}'"),
    'direct_hit': ('bool', 'False'),
    'distance_m': ('float', '0.0'),
    'effect_scale': ('float', '0.0'),
    'spatial_intersection_fraction': ('float', '0.0'),
    'pattern_weight': ('float', '1.0'),
    'orientation_weight': ('float', '1.0'),
    'receiver_exposure_fraction': ('float', '1.0'),
    'armor_transmission': ('float', '1.0'),
    'sampling_confidence': ('float', '1.0'),
    'load_intensity_scale': ('float', '1.0'),
    'fragment_energy_j': ('float', '0.0'),
    'fragment_density_per_m2': ('float', '0.0'),
    'penetration_margin': ('float', '0.0'),
    'blast_overpressure_kpa': ('float', '0.0'),
    'blast_impulse_kpa_ms': ('float', '0.0'),
    'blast_scaled_distance_m_kg13': ('float', '0.0'),
    'rod_cut_margin': ('float', '0.0'),
    'surface_incidence_cos': ('float', '0.0'),
    'load_source': ('str', '\'"unprojected"\''),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
