"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('header', 'component_name', 'component_system', 'component_redundancy_group_id', 'integrity_before', 'integrity_after', 'failure_mode', 'failure_severity', 'failure_probability', 'failure_sample')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('header', 'component_name', 'component_system', 'component_redundancy_group_id', 'integrity_before', 'integrity_after', 'failure_mode', 'failure_severity', 'failure_probability', 'failure_sample')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'header': ('object', "'{}'"),
    'component_name': ('str', "'{}'"),
    'component_system': ('str', "'{}'"),
    'component_redundancy_group_id': ('str', "'{}'"),
    'integrity_before': ('float', '1.0'),
    'integrity_after': ('float', '1.0'),
    'failure_mode': ('str', '\'"none"\''),
    'failure_severity': ('float', '0.0'),
    'failure_probability': ('float', '0.0'),
    'failure_sample': ('float', '1.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
