"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('component_name', 'component_system', 'component_redundancy_group_id', 'direct_hit', 'distance_m', 'effect_scale', 'component_dependency_propagation_count', 'component_dependency_target_system', 'component_dependency_edge_type', 'component_dependency_threshold', 'component_dependency_delay_s', 'component_dependency_direction', 'component_dependency_provenance', 'component_dependency_source_availability', 'component_dependency_effective_scale', 'component_dependency_propagated', 'mechanism_fragment_energy_j', 'mechanism_fragment_areal_density_per_m2', 'mechanism_penetration_margin', 'mechanism_blast_overpressure_kpa', 'mechanism_blast_impulse_kpa_ms', 'mechanism_blast_scaled_distance_m_kg13', 'mechanism_rod_cut_margin', 'mechanism_surface_incidence_cos')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('component_name', 'component_system', 'component_redundancy_group_id', 'direct_hit', 'distance_m', 'effect_scale', 'component_dependency_propagation_count', 'component_dependency_target_system', 'component_dependency_edge_type', 'component_dependency_threshold', 'component_dependency_delay_s', 'component_dependency_direction', 'component_dependency_provenance', 'component_dependency_source_availability', 'component_dependency_effective_scale', 'component_dependency_propagated', 'mechanism_fragment_energy_j', 'mechanism_fragment_areal_density_per_m2', 'mechanism_penetration_margin', 'mechanism_blast_overpressure_kpa', 'mechanism_blast_impulse_kpa_ms', 'mechanism_blast_scaled_distance_m_kg13', 'mechanism_rod_cut_margin', 'mechanism_surface_incidence_cos')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'component_name': ('str', "'{}'"),
    'component_system': ('str', "'{}'"),
    'component_redundancy_group_id': ('str', "'{}'"),
    'direct_hit': ('bool', 'False'),
    'distance_m': ('float', '0.0'),
    'effect_scale': ('float', '0.0'),
    'component_dependency_propagation_count': ('object', "'0'"),
    'component_dependency_target_system': ('str', "'{}'"),
    'component_dependency_edge_type': ('str', '\'"none"\''),
    'component_dependency_threshold': ('float', '1.0'),
    'component_dependency_delay_s': ('float', '0.0'),
    'component_dependency_direction': ('str', '\'"one_way"\''),
    'component_dependency_provenance': ('str', "'{}'"),
    'component_dependency_source_availability': ('float', '1.0'),
    'component_dependency_effective_scale': ('float', '0.0'),
    'component_dependency_propagated': ('bool', 'False'),
    'mechanism_fragment_energy_j': ('float', '0.0'),
    'mechanism_fragment_areal_density_per_m2': ('float', '0.0'),
    'mechanism_penetration_margin': ('float', '0.0'),
    'mechanism_blast_overpressure_kpa': ('float', '0.0'),
    'mechanism_blast_impulse_kpa_ms': ('float', '0.0'),
    'mechanism_blast_scaled_distance_m_kg13': ('float', '0.0'),
    'mechanism_rod_cut_margin': ('float', '0.0'),
    'mechanism_surface_incidence_cos': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
