"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('report_id', 'target', 'source_event_id', 'hp_delta', 'system_health_delta', 'platform_damage_state_delta', 'mission_kill', 'mobility_kill', 'sensor_kill', 'survivability_kill', 'forced_landing', 'flight_control_kill', 'propulsion_kill', 'crew_kill', 'loss_state_from', 'loss_state_to', 'destroyed', 'report_time_s', 'producer_node_id')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('report_id', 'target', 'source_event_id', 'hp_delta', 'system_health_delta', 'platform_damage_state_delta', 'mission_kill', 'mobility_kill', 'sensor_kill', 'survivability_kill', 'forced_landing', 'flight_control_kill', 'propulsion_kill', 'crew_kill', 'loss_state_from', 'loss_state_to', 'destroyed', 'report_time_s', 'producer_node_id')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'report_id': ('object', "'0'"),
    'target': ('object', "'{}'"),
    'source_event_id': ('object', "'0'"),
    'hp_delta': ('float', '0.0'),
    'system_health_delta': ('float', '0.0'),
    'platform_damage_state_delta': ('str', "'{}'"),
    'mission_kill': ('bool', 'False'),
    'mobility_kill': ('bool', 'False'),
    'sensor_kill': ('bool', 'False'),
    'survivability_kill': ('bool', 'False'),
    'forced_landing': ('bool', 'False'),
    'flight_control_kill': ('bool', 'False'),
    'propulsion_kill': ('bool', 'False'),
    'crew_kill': ('bool', 'False'),
    'loss_state_from': ('str', '\'"unknown"\''),
    'loss_state_to': ('str', '\'"unknown"\''),
    'destroyed': ('bool', 'False'),
    'report_time_s': ('float', '0.0'),
    'producer_node_id': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
