"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('trace_id', 'parent_trace_id', 'chain_id', 'track_id', 'launch_request_id', 'launch_event_id', 'munition', 'effects_event_id', 'damage_report_id', 'observation_packet_version', 'source_snapshot_version', 'barrier_id', 'barrier_detail', 'source_time_s', 'source_node_id', 'export_node_id')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('trace_id', 'parent_trace_id', 'chain_id', 'track_id', 'launch_request_id', 'launch_event_id', 'munition', 'effects_event_id', 'damage_report_id', 'observation_packet_version', 'source_snapshot_version', 'barrier_id', 'barrier_detail', 'source_time_s', 'source_node_id', 'export_node_id')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'trace_id': ('object', "'0'"),
    'parent_trace_id': ('object', "'0'"),
    'chain_id': ('object', "'0'"),
    'track_id': ('object', "'0'"),
    'launch_request_id': ('object', "'0'"),
    'launch_event_id': ('object', "'0'"),
    'munition': ('object', "'{}'"),
    'effects_event_id': ('object', "'0'"),
    'damage_report_id': ('object', "'0'"),
    'observation_packet_version': ('object', "'0'"),
    'source_snapshot_version': ('object', "'0'"),
    'barrier_id': ('str', '\'"export"\''),
    'barrier_detail': ('str', '\'"maintained_facade_export"\''),
    'source_time_s': ('float', '0.0'),
    'source_node_id': ('str', "'{}'"),
    'export_node_id': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
