"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('snapshot_version', 'barrier_id', 'barrier_sequence', 'barrier_detail', 'source_time_s', 'producer_node_id', 'packet_provenance', 'diagnostics_provenance', 'refs', 'trace_ids', 'track_packets', 'launch_requests', 'launch_events', 'munition_lifecycle_packets', 'effects_events', 'nearest_approach_events', 'fuze_evaluation_events', 'warhead_mechanism_events', 'spatial_coverage_events', 'component_load_events', 'component_damage_events', 'platform_consequence_events', 'structural_breakup_events', 'lifecycle_transition_events', 'training_projection_events', 'damage_reports', 'diagnostics_traces')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('snapshot_version', 'barrier_id', 'barrier_sequence', 'barrier_detail', 'source_time_s', 'producer_node_id', 'packet_provenance', 'diagnostics_provenance', 'refs', 'trace_ids', 'track_packets', 'launch_requests', 'launch_events', 'munition_lifecycle_packets', 'effects_events', 'nearest_approach_events', 'fuze_evaluation_events', 'warhead_mechanism_events', 'spatial_coverage_events', 'component_load_events', 'component_damage_events', 'platform_consequence_events', 'structural_breakup_events', 'lifecycle_transition_events', 'training_projection_events', 'damage_reports', 'diagnostics_traces')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'snapshot_version': ('object', "'0'"),
    'barrier_id': ('str', '\'"export"\''),
    'barrier_sequence': ('object', "'0'"),
    'barrier_detail': ('str', '\'"maintained_facade_export"\''),
    'source_time_s': ('float', '0.0'),
    'producer_node_id': ('str', "'{}'"),
    'packet_provenance': ('object', "'make_information_state_source(kPolicyInformationStateTrackState, kPolicySourceLabelTrackStatePacket, kPolicyMaintainedStatusMaintained)'"),
    'diagnostics_provenance': ('object', "'make_information_state_source(kPolicyInformationStateDecisionBelief, kPolicySourceLabelWorldTruthDiagnostics, kPolicyMaintainedStatusDiagnosticsOnly)'"),
    'refs': ('object', "'{}'"),
    'trace_ids': ('object', "'{}'"),
    'track_packets': ('object', "'{}'"),
    'launch_requests': ('object', "'{}'"),
    'launch_events': ('object', "'{}'"),
    'munition_lifecycle_packets': ('object', "'{}'"),
    'effects_events': ('object', "'{}'"),
    'nearest_approach_events': ('object', "'{}'"),
    'fuze_evaluation_events': ('object', "'{}'"),
    'warhead_mechanism_events': ('object', "'{}'"),
    'spatial_coverage_events': ('object', "'{}'"),
    'component_load_events': ('object', "'{}'"),
    'component_damage_events': ('object', "'{}'"),
    'platform_consequence_events': ('object', "'{}'"),
    'structural_breakup_events': ('object', "'{}'"),
    'lifecycle_transition_events': ('object', "'{}'"),
    'training_projection_events': ('object', "'{}'"),
    'damage_reports': ('object', "'{}'"),
    'diagnostics_traces': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
