"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('refs', 'trace_ids', 'include_track_packets', 'include_launch_requests', 'include_launch_events', 'include_munition_lifecycle_packets', 'include_effects_events', 'include_damage_reports', 'include_diagnostics_traces')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('refs', 'trace_ids', 'include_track_packets', 'include_launch_requests', 'include_launch_events', 'include_munition_lifecycle_packets', 'include_effects_events', 'include_damage_reports', 'include_diagnostics_traces')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'refs': ('object', "'{}'"),
    'trace_ids': ('object', "'{}'"),
    'include_track_packets': ('bool', 'True'),
    'include_launch_requests': ('bool', 'True'),
    'include_launch_events': ('bool', 'True'),
    'include_munition_lifecycle_packets': ('bool', 'True'),
    'include_effects_events': ('bool', 'True'),
    'include_damage_reports': ('bool', 'True'),
    'include_diagnostics_traces': ('bool', 'True'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
