"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'outcome_state', 'component_hit_count', 'component_failure_count', 'primary_component_name', 'primary_component_system', 'primary_component_integrity', 'redundancy_group_availability', 'air_system_hit_flags', 'air_system_spatial_scales', 'vulnerability_scale_trace')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'outcome_state', 'component_hit_count', 'component_failure_count', 'primary_component_name', 'primary_component_system', 'primary_component_integrity', 'redundancy_group_availability', 'air_system_hit_flags', 'air_system_spatial_scales', 'vulnerability_scale_trace')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'owner_stage': ('str', '\'"consequence_projection"\''),
    'outcome_state': ('str', '\'"unknown"\''),
    'component_hit_count': ('object', "'0'"),
    'component_failure_count': ('object', "'0'"),
    'primary_component_name': ('str', "'{}'"),
    'primary_component_system': ('str', "'{}'"),
    'primary_component_integrity': ('float', '1.0'),
    'redundancy_group_availability': ('float', '1.0'),
    'air_system_hit_flags': ('str', "'{}'"),
    'air_system_spatial_scales': ('str', "'{}'"),
    'vulnerability_scale_trace': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
