"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('schema_version', 'schema_name', 'runtime_dto_authority', 'runtime_parameter_retuning', 'calibration_authority', 'real_world_pk', 'approach_fact', 'fuze_decision', 'warhead_load_field', 'target_susceptibility', 'component_responses', 'consequence_projection')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('schema_version', 'schema_name', 'runtime_dto_authority', 'runtime_parameter_retuning', 'calibration_authority', 'real_world_pk', 'approach_fact', 'fuze_decision', 'warhead_load_field', 'target_susceptibility', 'component_responses', 'consequence_projection')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'schema_version': ('object', "'1'"),
    'schema_name': ('str', '\'"a2.kill_chain_runtime_facade.v1"\''),
    'runtime_dto_authority': ('bool', 'True'),
    'runtime_parameter_retuning': ('bool', 'False'),
    'calibration_authority': ('bool', 'False'),
    'real_world_pk': ('bool', 'False'),
    'approach_fact': ('object', "'{}'"),
    'fuze_decision': ('object', "'{}'"),
    'warhead_load_field': ('object', "'{}'"),
    'target_susceptibility': ('object', "'{}'"),
    'component_responses': ('object', "'{}'"),
    'consequence_projection': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
