"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'source_current_owner_stage', 'source_row_index', 'component_name', 'component_system', 'component_redundancy_group_id', 'threshold_scale', 'failure_probability', 'failure_sample', 'failure_probability_source', 'failure_probability_calibrated', 'failure_probability_evidence_dataset_ref', 'failure_probability_evidence_row_id', 'failure_probability_evidence_source_ref', 'failure_probability_evidence_provenance', 'failure_probability_authority', 'failure_probability_component_specific', 'failure_probability_weapon_family', 'failure_probability_aspect_bucket', 'failure_probability_closure_bucket', 'failure_probability_miss_distance_bucket', 'failure_probability_evidence_component_name', 'failure_probability_evidence_component_system', 'failure_probability_evidence_component_redundancy_group_id', 'failure_mode', 'failure_severity', 'failure_mode_names', 'failure_mode_severities', 'failure_mode_source', 'failure_mode_authority', 'integrity_before', 'integrity_after', 'redundancy_group_availability_before', 'redundancy_group_availability_after')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'source_current_owner_stage', 'source_row_index', 'component_name', 'component_system', 'component_redundancy_group_id', 'threshold_scale', 'failure_probability', 'failure_sample', 'failure_probability_source', 'failure_probability_calibrated', 'failure_probability_evidence_dataset_ref', 'failure_probability_evidence_row_id', 'failure_probability_evidence_source_ref', 'failure_probability_evidence_provenance', 'failure_probability_authority', 'failure_probability_component_specific', 'failure_probability_weapon_family', 'failure_probability_aspect_bucket', 'failure_probability_closure_bucket', 'failure_probability_miss_distance_bucket', 'failure_probability_evidence_component_name', 'failure_probability_evidence_component_system', 'failure_probability_evidence_component_redundancy_group_id', 'failure_mode', 'failure_severity', 'failure_mode_names', 'failure_mode_severities', 'failure_mode_source', 'failure_mode_authority', 'integrity_before', 'integrity_after', 'redundancy_group_availability_before', 'redundancy_group_availability_after')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'owner_stage': ('str', '\'"component_response"\''),
    'source_current_owner_stage': ('str', '\'"component_response_row"\''),
    'source_row_index': ('object', "'0'"),
    'component_name': ('str', "'{}'"),
    'component_system': ('str', "'{}'"),
    'component_redundancy_group_id': ('str', "'{}'"),
    'threshold_scale': ('float', '1.0'),
    'failure_probability': ('float', '0.0'),
    'failure_sample': ('float', '1.0'),
    'failure_probability_source': ('str', '\'"none"\''),
    'failure_probability_calibrated': ('bool', 'False'),
    'failure_probability_evidence_dataset_ref': ('str', "'{}'"),
    'failure_probability_evidence_row_id': ('str', "'{}'"),
    'failure_probability_evidence_source_ref': ('str', "'{}'"),
    'failure_probability_evidence_provenance': ('str', "'{}'"),
    'failure_probability_authority': ('bool', 'False'),
    'failure_probability_component_specific': ('bool', 'False'),
    'failure_probability_weapon_family': ('str', '\'"unknown"\''),
    'failure_probability_aspect_bucket': ('str', '\'"unknown"\''),
    'failure_probability_closure_bucket': ('str', '\'"unknown"\''),
    'failure_probability_miss_distance_bucket': ('str', '\'"unknown"\''),
    'failure_probability_evidence_component_name': ('str', "'{}'"),
    'failure_probability_evidence_component_system': ('str', "'{}'"),
    'failure_probability_evidence_component_redundancy_group_id': ('str', "'{}'"),
    'failure_mode': ('str', '\'"none"\''),
    'failure_severity': ('float', '0.0'),
    'failure_mode_names': ('object', "'{}'"),
    'failure_mode_severities': ('object', "'{}'"),
    'failure_mode_source': ('str', '\'"none"\''),
    'failure_mode_authority': ('bool', 'False'),
    'integrity_before': ('float', '1.0'),
    'integrity_after': ('float', '1.0'),
    'redundancy_group_availability_before': ('float', '1.0'),
    'redundancy_group_availability_after': ('float', '1.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
