"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'vulnerability_profile_present', 'vulnerability_profile_synthetic', 'calibrated_evidence', 'pk_authority', 'deterministic_fuze_authority', 'calibration_status', 'aspect_bucket', 'family_scale', 'aspect_scale', 'closure_scale', 'miss_distance_scale', 'effect_scale')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'vulnerability_profile_present', 'vulnerability_profile_synthetic', 'calibrated_evidence', 'pk_authority', 'deterministic_fuze_authority', 'calibration_status', 'aspect_bucket', 'family_scale', 'aspect_scale', 'closure_scale', 'miss_distance_scale', 'effect_scale')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'owner_stage': ('str', '\'"target_susceptibility"\''),
    'vulnerability_profile_present': ('bool', 'False'),
    'vulnerability_profile_synthetic': ('bool', 'True'),
    'calibrated_evidence': ('bool', 'False'),
    'pk_authority': ('bool', 'False'),
    'deterministic_fuze_authority': ('bool', 'False'),
    'calibration_status': ('str', '\'"none"\''),
    'aspect_bucket': ('str', '\'"unknown"\''),
    'family_scale': ('float', '1.0'),
    'aspect_scale': ('float', '1.0'),
    'closure_scale': ('float', '1.0'),
    'miss_distance_scale': ('float', '1.0'),
    'effect_scale': ('float', '1.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
