"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'fuze_type', 'detonated', 'outcome_state', 'detonation_time_s', 'detonation_probability', 'fuze_quality', 'sensor_opportunity_score', 'terminal_track_valid', 'target_detected', 'target_detection_confidence', 'target_detection_threshold', 'detonation_point_source')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('owner_stage', 'fuze_type', 'detonated', 'outcome_state', 'detonation_time_s', 'detonation_probability', 'fuze_quality', 'sensor_opportunity_score', 'terminal_track_valid', 'target_detected', 'target_detection_confidence', 'target_detection_threshold', 'detonation_point_source')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'owner_stage': ('str', '\'"fuze_decision"\''),
    'fuze_type': ('str', '\'"unknown"\''),
    'detonated': ('bool', 'False'),
    'outcome_state': ('str', '\'"unknown"\''),
    'detonation_time_s': ('float', '0.0'),
    'detonation_probability': ('float', '0.0'),
    'fuze_quality': ('float', '0.0'),
    'sensor_opportunity_score': ('float', '0.0'),
    'terminal_track_valid': ('bool', 'False'),
    'target_detected': ('bool', 'False'),
    'target_detection_confidence': ('float', '0.0'),
    'target_detection_threshold': ('float', '0.0'),
    'detonation_point_source': ('str', '\'"unknown"\''),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
