"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('event_id', 'request_id', 'accepted', 'rejection_reason', 'selected_launcher', 'selected_munition', 'ammo_delta', 'cooldown_delta_s', 'spawned_munition', 'has_spawned_munition', 'event_time_s', 'producer_node_id')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('event_id', 'request_id', 'accepted', 'rejection_reason', 'selected_launcher', 'selected_munition', 'ammo_delta', 'cooldown_delta_s', 'spawned_munition', 'has_spawned_munition', 'event_time_s', 'producer_node_id')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'event_id': ('object', "'0'"),
    'request_id': ('object', "'0'"),
    'accepted': ('bool', 'False'),
    'rejection_reason': ('str', "'{}'"),
    'selected_launcher': ('str', "'{}'"),
    'selected_munition': ('str', "'{}'"),
    'ammo_delta': ('int', '0'),
    'cooldown_delta_s': ('float', '0.0'),
    'spawned_munition': ('object', "'{}'"),
    'has_spawned_munition': ('bool', 'False'),
    'event_time_s': ('float', '0.0'),
    'producer_node_id': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
