"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('request_id', 'shooter', 'target_entity', 'has_target_entity', 'target_track_id', 'has_target_track', 'station_id', 'mount_id', 'requested_munition_family', 'authority', 'requested_time_s', 'merge_policy')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('request_id', 'shooter', 'target_entity', 'has_target_entity', 'target_track_id', 'has_target_track', 'station_id', 'mount_id', 'requested_munition_family', 'authority', 'requested_time_s', 'merge_policy')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'request_id': ('object', "'0'"),
    'shooter': ('object', "'{}'"),
    'target_entity': ('object', "'{}'"),
    'has_target_entity': ('bool', 'False'),
    'target_track_id': ('object', "'0'"),
    'has_target_track': ('bool', 'False'),
    'station_id': ('str', "'{}'"),
    'mount_id': ('str', "'{}'"),
    'requested_munition_family': ('str', "'{}'"),
    'authority': ('str', '\'"unspecified"\''),
    'requested_time_s': ('float', '0.0'),
    'merge_policy': ('str', '\'"reject_on_conflict"\''),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
