"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('shared_core', 'phase_id', 'element_phase_id', 'air_recovery', 'formation_mode_id', 'join_required_flag', 'rejoin_required_flag', 'air_takeoff', 'air_formation', 'naval_command_authority', 'ground_static_status')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('shared_core', 'phase_id', 'element_phase_id', 'air_recovery', 'formation_mode_id', 'join_required_flag', 'rejoin_required_flag', 'air_takeoff', 'air_formation', 'naval_command_authority', 'ground_static_status')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'shared_core': ('object', "'{}'"),
    'phase_id': ('object', "'LeaderPhase::Idle'"),
    'element_phase_id': ('int', '0'),
    'air_recovery': ('object', "'{}'"),
    'formation_mode_id': ('object', "'FormationMode::Unspecified'"),
    'join_required_flag': ('bool', 'False'),
    'rejoin_required_flag': ('bool', 'False'),
    'air_takeoff': ('object', "'{}'"),
    'air_formation': ('object', "'{}'"),
    'naval_command_authority': ('object', "'{}'"),
    'ground_static_status': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
