"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('schema_version', 'chain_id', 'event_id', 'parent_event_id', 'stage', 'status', 'reason', 'source_time_s', 'source_frame', 'munition', 'shooter', 'target', 'producer_node_id', 'fidelity_mode', 'evidence_level', 'observation_mode', 'consumer_visibility', 'confidence')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('schema_version', 'chain_id', 'event_id', 'parent_event_id', 'stage', 'status', 'reason', 'source_time_s', 'source_frame', 'munition', 'shooter', 'target', 'producer_node_id', 'fidelity_mode', 'evidence_level', 'observation_mode', 'consumer_visibility', 'confidence')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'schema_version': ('object', "'kLethalityChainContractSchemaVersion'"),
    'chain_id': ('object', "'0'"),
    'event_id': ('object', "'0'"),
    'parent_event_id': ('object', "'0'"),
    'stage': ('str', '\'"unknown"\''),
    'status': ('str', '\'"not_evaluated"\''),
    'reason': ('str', "'{}'"),
    'source_time_s': ('float', '0.0'),
    'source_frame': ('object', "'0'"),
    'munition': ('object', "'{}'"),
    'shooter': ('object', "'{}'"),
    'target': ('object', "'{}'"),
    'producer_node_id': ('str', "'{}'"),
    'fidelity_mode': ('str', '\'"unspecified"\''),
    'evidence_level': ('str', '\'"uncalibrated"\''),
    'observation_mode': ('str', "'std::string(kLethalityObservationModeSampledRuntime)'"),
    'consumer_visibility': ('str', "'std::string(kLethalityConsumerVisibilityDiagnosticsAndTraining)'"),
    'confidence': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
