"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'active_wp_idx', 'total_wps', 'selected_steerpoint', 'steerpoint_mode_code', 'dist_m', 'xtk_m', 'dtg_m', 'direct_bearing_deg', 'desired_leg_track_deg', 'bearing_rel_deg', 'altitude_delta_m', 'cdi_norm', 'track_angle_error_deg', 'next_turn_deg', 'distance_to_turn_m', 'own_heading_deg', 'ground_track_deg', 'reference_speed_mps')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'active_wp_idx', 'total_wps', 'selected_steerpoint', 'steerpoint_mode_code', 'dist_m', 'xtk_m', 'dtg_m', 'direct_bearing_deg', 'desired_leg_track_deg', 'bearing_rel_deg', 'altitude_delta_m', 'cdi_norm', 'track_angle_error_deg', 'next_turn_deg', 'distance_to_turn_m', 'own_heading_deg', 'ground_track_deg', 'reference_speed_mps'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'active_wp_idx': ('float', '0.0'),
    'total_wps': ('float', '0.0'),
    'selected_steerpoint': ('float', '0.0'),
    'steerpoint_mode_code': ('float', '0.0'),
    'dist_m': ('float', '0.0'),
    'xtk_m': ('float', '0.0'),
    'dtg_m': ('float', '0.0'),
    'direct_bearing_deg': ('float', '0.0'),
    'desired_leg_track_deg': ('float', '0.0'),
    'bearing_rel_deg': ('float', '0.0'),
    'altitude_delta_m': ('float', '0.0'),
    'cdi_norm': ('float', '0.0'),
    'track_angle_error_deg': ('float', '0.0'),
    'next_turn_deg': ('float', '0.0'),
    'distance_to_turn_m': ('float', '0.0'),
    'own_heading_deg': ('float', '0.0'),
    'ground_track_deg': ('float', '0.0'),
    'reference_speed_mps': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
