"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('own_altitude_m', 'truth_heading_deg', 'truth_speed_mps', 'inst_heading_deg', 'inst_ground_track_deg', 'inst_ias_mps', 'waypoint_altitude_m', 'cdi_full_scale_m')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('own_altitude_m', 'truth_heading_deg', 'truth_speed_mps', 'inst_heading_deg', 'inst_ground_track_deg', 'inst_ias_mps', 'waypoint_altitude_m', 'cdi_full_scale_m')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'own_altitude_m': ('float', '0.0'),
    'truth_heading_deg': ('float', '0.0'),
    'truth_speed_mps': ('float', '0.0'),
    'inst_heading_deg': ('float', '0.0'),
    'inst_ground_track_deg': ('float', '0.0'),
    'inst_ias_mps': ('float', '0.0'),
    'waypoint_altitude_m': ('float', '0.0'),
    'cdi_full_scale_m': ('float', '1500.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
