"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('packet_id', 'munition', 'attacker', 'target_entity', 'has_target_entity', 'target_track_id', 'has_target_track', 'launch_event_id', 'active', 'seeker_mode', 'guidance_cadence_s', 'track_memory_state', 'fuel_remaining_fraction', 'burnout', 'max_flight_time_s', 'fuze_state', 'source_time_s')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('packet_id', 'munition', 'attacker', 'target_entity', 'has_target_entity', 'target_track_id', 'has_target_track', 'launch_event_id', 'active', 'seeker_mode', 'guidance_cadence_s', 'track_memory_state', 'fuel_remaining_fraction', 'burnout', 'max_flight_time_s', 'fuze_state', 'source_time_s')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'packet_id': ('object', "'0'"),
    'munition': ('object', "'{}'"),
    'attacker': ('object', "'{}'"),
    'target_entity': ('object', "'{}'"),
    'has_target_entity': ('bool', 'False'),
    'target_track_id': ('object', "'0'"),
    'has_target_track': ('bool', 'False'),
    'launch_event_id': ('object', "'0'"),
    'active': ('bool', 'False'),
    'seeker_mode': ('str', '\'"unknown"\''),
    'guidance_cadence_s': ('float', '0.0'),
    'track_memory_state': ('str', '\'"unknown"\''),
    'fuel_remaining_fraction': ('float', '0.0'),
    'burnout': ('bool', 'False'),
    'max_flight_time_s': ('float', '0.0'),
    'fuze_state': ('str', '\'"unknown"\''),
    'source_time_s': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
