"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('header', 'nearest_approach_time_s', 'miss_distance_m', 'local_forward_m', 'local_right_m', 'local_up_m', 'closure_mps', 'aspect_bucket')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('header', 'nearest_approach_time_s', 'miss_distance_m', 'local_forward_m', 'local_right_m', 'local_up_m', 'closure_mps', 'aspect_bucket')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'header': ('object', "'{}'"),
    'nearest_approach_time_s': ('float', '0.0'),
    'miss_distance_m': ('float', '0.0'),
    'local_forward_m': ('float', '0.0'),
    'local_right_m': ('float', '0.0'),
    'local_up_m': ('float', '0.0'),
    'closure_mps': ('float', '0.0'),
    'aspect_bucket': ('str', '\'"unknown"\''),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
