"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'matched', 'unknown_property', 'status0', 'status1', 'status2', 'status_count', 'success_runway_cross_penalty', 'success_ground_track_error_penalty', 'objective_bonus')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'matched', 'unknown_property', 'status0', 'status1', 'status2', 'status_count', 'success_runway_cross_penalty', 'success_ground_track_error_penalty', 'objective_bonus'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'matched': ('bool', 'False'),
    'unknown_property': ('bool', 'False'),
    'status0': ('float', '0.0'),
    'status1': ('float', '0.0'),
    'status2': ('float', '0.0'),
    'status_count': ('int', '0'),
    'success_runway_cross_penalty': ('float', '0.0'),
    'success_ground_track_error_penalty': ('float', '0.0'),
    'objective_bonus': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
