"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('runway_cross_penalty_weight', 'runway_cross_deadband_m', 'runway_cross_norm_m', 'runway_cross_power', 'runway_cross_clip', 'ground_track_penalty_weight', 'ground_track_deadband_deg', 'ground_track_norm_deg', 'ground_track_power', 'ground_track_clip')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('runway_cross_penalty_weight', 'runway_cross_deadband_m', 'runway_cross_norm_m', 'runway_cross_power', 'runway_cross_clip', 'ground_track_penalty_weight', 'ground_track_deadband_deg', 'ground_track_norm_deg', 'ground_track_power', 'ground_track_clip')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'runway_cross_penalty_weight': ('float', '0.0'),
    'runway_cross_deadband_m': ('float', '0.0'),
    'runway_cross_norm_m': ('float', '20.0'),
    'runway_cross_power': ('float', '2.0'),
    'runway_cross_clip': ('float', '0.0'),
    'ground_track_penalty_weight': ('float', '0.0'),
    'ground_track_deadband_deg': ('float', '0.0'),
    'ground_track_norm_deg': ('float', '10.0'),
    'ground_track_power': ('float', '2.0'),
    'ground_track_clip': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
