"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('altitude_m', 'altitude_agl_m', 'speed_mps', 'ground_speed_mps', 'gear_fraction', 'heading_error_deg', 'command_code', 'ground_track_error_deg', 'has_runway_cross_m', 'runway_cross_m', 'has_runway_from_threshold_m', 'runway_from_threshold_m', 'on_runway_geom', 'on_runway_task', 'on_ground', 'sink_rate_abs_mps', 'ils_localizer_abs', 'ils_glideslope_abs', 'dme_m', 'heading_deg', 'x_m', 'y_m', 'target_altitude_m', 'target_speed_mps', 'target_heading_deg', 'self_active', 'target_active', 'self_health', 'target_health', 'missiles_remaining', 'has_target_range_m', 'target_range_m')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('altitude_m', 'altitude_agl_m', 'speed_mps', 'ground_speed_mps', 'gear_fraction', 'heading_error_deg', 'command_code', 'ground_track_error_deg', 'has_runway_cross_m', 'runway_cross_m', 'has_runway_from_threshold_m', 'runway_from_threshold_m', 'on_runway_geom', 'on_runway_task', 'on_ground', 'sink_rate_abs_mps', 'ils_localizer_abs', 'ils_glideslope_abs', 'dme_m', 'heading_deg', 'x_m', 'y_m', 'target_altitude_m', 'target_speed_mps', 'target_heading_deg', 'self_active', 'target_active', 'self_health', 'target_health', 'missiles_remaining', 'has_target_range_m', 'target_range_m')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'altitude_m': ('float', '0.0'),
    'altitude_agl_m': ('float', '0.0'),
    'speed_mps': ('float', '0.0'),
    'ground_speed_mps': ('float', '0.0'),
    'gear_fraction': ('float', '0.0'),
    'heading_error_deg': ('float', '0.0'),
    'command_code': ('float', '0.0'),
    'ground_track_error_deg': ('float', '0.0'),
    'has_runway_cross_m': ('bool', 'False'),
    'runway_cross_m': ('float', '0.0'),
    'has_runway_from_threshold_m': ('bool', 'False'),
    'runway_from_threshold_m': ('float', '0.0'),
    'on_runway_geom': ('bool', 'False'),
    'on_runway_task': ('bool', 'False'),
    'on_ground': ('bool', 'False'),
    'sink_rate_abs_mps': ('float', '0.0'),
    'ils_localizer_abs': ('float', '0.0'),
    'ils_glideslope_abs': ('float', '0.0'),
    'dme_m': ('float', '0.0'),
    'heading_deg': ('float', '0.0'),
    'x_m': ('float', '0.0'),
    'y_m': ('float', '0.0'),
    'target_altitude_m': ('float', '0.0'),
    'target_speed_mps': ('float', '0.0'),
    'target_heading_deg': ('float', '0.0'),
    'self_active': ('bool', 'True'),
    'target_active': ('bool', 'False'),
    'self_health': ('float', '100.0'),
    'target_health': ('float', '0.0'),
    'missiles_remaining': ('float', '0.0'),
    'has_target_range_m': ('bool', 'False'),
    'target_range_m': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
