"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('compatible', 'major_compatible', 'required_fields_satisfied', 'optional_field_drift_allowed', 'missing_required_fields', 'unknown_optional_fields', 'missing_optional_fields')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('compatible', 'major_compatible', 'required_fields_satisfied', 'optional_field_drift_allowed', 'missing_required_fields', 'unknown_optional_fields', 'missing_optional_fields')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'compatible': ('bool', 'False'),
    'major_compatible': ('bool', 'False'),
    'required_fields_satisfied': ('bool', 'False'),
    'optional_field_drift_allowed': ('bool', 'False'),
    'missing_required_fields': ('object', "'{}'"),
    'unknown_optional_fields': ('object', "'{}'"),
    'missing_optional_fields': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
