"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('header', 'mission_capability_before', 'mission_capability_after', 'mobility_capability_before', 'mobility_capability_after', 'sensor_capability_before', 'sensor_capability_after', 'survivability_capability_before', 'survivability_capability_after', 'mission_kill', 'mobility_kill', 'sensor_kill', 'survivability_kill', 'flight_control_kill', 'propulsion_kill', 'forced_landing', 'crew_kill', 'control_delta', 'engine_delta', 'fuel_leak_delta', 'fire_state', 'aircraft_damage_state_before', 'aircraft_damage_state_after', 'aircraft_damage_state_delta', 'air_system_hit_flags', 'air_system_spatial_scales', 'vulnerability_scale_trace', 'loss_state_from', 'loss_state_to')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('header', 'mission_capability_before', 'mission_capability_after', 'mobility_capability_before', 'mobility_capability_after', 'sensor_capability_before', 'sensor_capability_after', 'survivability_capability_before', 'survivability_capability_after', 'mission_kill', 'mobility_kill', 'sensor_kill', 'survivability_kill', 'flight_control_kill', 'propulsion_kill', 'forced_landing', 'crew_kill', 'control_delta', 'engine_delta', 'fuel_leak_delta', 'fire_state', 'aircraft_damage_state_before', 'aircraft_damage_state_after', 'aircraft_damage_state_delta', 'air_system_hit_flags', 'air_system_spatial_scales', 'vulnerability_scale_trace', 'loss_state_from', 'loss_state_to')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'header': ('object', "'{}'"),
    'mission_capability_before': ('float', '1.0'),
    'mission_capability_after': ('float', '1.0'),
    'mobility_capability_before': ('float', '1.0'),
    'mobility_capability_after': ('float', '1.0'),
    'sensor_capability_before': ('float', '1.0'),
    'sensor_capability_after': ('float', '1.0'),
    'survivability_capability_before': ('float', '1.0'),
    'survivability_capability_after': ('float', '1.0'),
    'mission_kill': ('bool', 'False'),
    'mobility_kill': ('bool', 'False'),
    'sensor_kill': ('bool', 'False'),
    'survivability_kill': ('bool', 'False'),
    'flight_control_kill': ('bool', 'False'),
    'propulsion_kill': ('bool', 'False'),
    'forced_landing': ('bool', 'False'),
    'crew_kill': ('bool', 'False'),
    'control_delta': ('float', '0.0'),
    'engine_delta': ('float', '0.0'),
    'fuel_leak_delta': ('float', '0.0'),
    'fire_state': ('str', '\'"unknown"\''),
    'aircraft_damage_state_before': ('str', "'{}'"),
    'aircraft_damage_state_after': ('str', "'{}'"),
    'aircraft_damage_state_delta': ('str', "'{}'"),
    'air_system_hit_flags': ('str', "'{}'"),
    'air_system_spatial_scales': ('str', "'{}'"),
    'vulnerability_scale_trace': ('str', "'{}'"),
    'loss_state_from': ('str', '\'"unknown"\''),
    'loss_state_to': ('str', '\'"unknown"\''),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
