"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('plan_id', 'source_request_kind', 'source_type_name', 'capability_bundle_id', 'resolved_platform_definition_ref', 'materialization_strategy', 'template_evidence_ref', 'resolution_evidence_ref', 'materialization_evidence_ref', 'evidence_refs', 'resolved_capabilities', 'rejected_capability_ids', 'type_name_projection_preserved', 'admitted', 'rejection_reason', 'diagnostics_reason')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('plan_id', 'source_request_kind', 'source_type_name', 'capability_bundle_id', 'resolved_platform_definition_ref', 'materialization_strategy', 'template_evidence_ref', 'resolution_evidence_ref', 'materialization_evidence_ref', 'evidence_refs', 'resolved_capabilities', 'rejected_capability_ids', 'type_name_projection_preserved', 'admitted', 'rejection_reason', 'diagnostics_reason')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'plan_id': ('str', "'{}'"),
    'source_request_kind': ('str', "'std::string(kPlatformSpawnRequestKindTypeNameProjection)'"),
    'source_type_name': ('str', "'{}'"),
    'capability_bundle_id': ('str', "'{}'"),
    'resolved_platform_definition_ref': ('str', "'{}'"),
    'materialization_strategy': ('str', "'std::string(kPlatformMaterializationStrategyFactoryProjection)'"),
    'template_evidence_ref': ('str', "'{}'"),
    'resolution_evidence_ref': ('str', "'{}'"),
    'materialization_evidence_ref': ('str', "'{}'"),
    'evidence_refs': ('object', "'{}'"),
    'resolved_capabilities': ('object', "'{}'"),
    'rejected_capability_ids': ('object', "'{}'"),
    'type_name_projection_preserved': ('bool', 'True'),
    'admitted': ('bool', 'False'),
    'rejection_reason': ('str', "'{}'"),
    'diagnostics_reason': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
