"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('comparable', 'comparison_id', 'parent_worldline_id', 'branch_worldline_id', 'barrier_id', 'dx', 'dy', 'dz', 'dvx', 'dvy', 'dvz', 'dheading', 'evidence_refs')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('comparable', 'comparison_id', 'parent_worldline_id', 'branch_worldline_id', 'barrier_id', 'dx', 'dy', 'dz', 'dvx', 'dvy', 'dvz', 'dheading', 'evidence_refs')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'comparable': ('bool', 'False'),
    'comparison_id': ('str', "'{}'"),
    'parent_worldline_id': ('str', "'{}'"),
    'branch_worldline_id': ('str', "'{}'"),
    'barrier_id': ('str', '\'"counterfactual_selected_slice"\''),
    'dx': ('float', '0.0'),
    'dy': ('float', '0.0'),
    'dz': ('float', '0.0'),
    'dvx': ('float', '0.0'),
    'dvy': ('float', '0.0'),
    'dvz': ('float', '0.0'),
    'dheading': ('float', '0.0'),
    'evidence_refs': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
