"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('domain', 'tick', 'node_id', 'decision', 'decision_reason', 'source', 'barrier_id', 'clock_domain', 'clock_merge_policy', 'cadence_merge_policy', 'relation', 'held', 'expired', 'deferred', 'diagnostics_only')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('domain', 'tick', 'node_id', 'decision', 'decision_reason', 'source', 'barrier_id', 'clock_domain', 'clock_merge_policy', 'cadence_merge_policy', 'relation', 'held', 'expired', 'deferred', 'diagnostics_only')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'domain': ('str', "'{}'"),
    'tick': ('object', "'0'"),
    'node_id': ('str', "'{}'"),
    'decision': ('str', '\'"skipped"\''),
    'decision_reason': ('str', "'{}'"),
    'source': ('str', "'{}'"),
    'barrier_id': ('str', "'{}'"),
    'clock_domain': ('str', "'{}'"),
    'clock_merge_policy': ('str', "'{}'"),
    'cadence_merge_policy': ('str', "'{}'"),
    'relation': ('str', "'{}'"),
    'held': ('bool', 'False'),
    'expired': ('bool', 'False'),
    'deferred': ('bool', 'False'),
    'diagnostics_only': ('bool', 'False'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
