"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('snapshot', 'expected_worldline_id', 'target_worldline_id', 'target_deterministic_seed', 'target_entity_ref', 'restore_barrier_id', 'allow_raw_authoritative_state_mutation', 'request_full_clone', 'request_resident_state_restore', 'request_exact_gpu_restore', 'evidence_refs')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('snapshot', 'expected_worldline_id', 'target_worldline_id', 'target_deterministic_seed', 'target_entity_ref', 'restore_barrier_id', 'allow_raw_authoritative_state_mutation', 'request_full_clone', 'request_resident_state_restore', 'request_exact_gpu_restore', 'evidence_refs')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'snapshot': ('object', "'{}'"),
    'expected_worldline_id': ('str', "'{}'"),
    'target_worldline_id': ('str', "'{}'"),
    'target_deterministic_seed': ('object', "'0'"),
    'target_entity_ref': ('object', "'{}'"),
    'restore_barrier_id': ('str', '\'"counterfactual_selected_slice"\''),
    'allow_raw_authoritative_state_mutation': ('bool', 'False'),
    'request_full_clone': ('bool', 'False'),
    'request_resident_state_restore': ('bool', 'False'),
    'request_exact_gpu_restore': ('bool', 'False'),
    'evidence_refs': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
