"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('baseline_setup', 'entity_ref', 'fidelity_request', 'deterministic_seed', 'replay_envelope_id', 'branch_point_id', 'branch_worldline_id', 'parent_worldline_id', 'restore_barrier_id', 'cadence_reason', 'mutation_dx', 'mutation_dy', 'mutation_dz', 'mutation_dvx', 'mutation_dvy', 'mutation_dvz', 'mutation_dheading', 'allow_raw_authoritative_state_mutation', 'evidence_refs')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('baseline_setup', 'entity_ref', 'fidelity_request', 'deterministic_seed', 'replay_envelope_id', 'branch_point_id', 'branch_worldline_id', 'parent_worldline_id', 'restore_barrier_id', 'cadence_reason', 'mutation_dx', 'mutation_dy', 'mutation_dz', 'mutation_dvx', 'mutation_dvy', 'mutation_dvz', 'mutation_dheading', 'allow_raw_authoritative_state_mutation', 'evidence_refs')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'baseline_setup': ('object', "'{}'"),
    'entity_ref': ('object', "'{}'"),
    'fidelity_request': ('object', "'{}'"),
    'deterministic_seed': ('object', "'0'"),
    'replay_envelope_id': ('str', "'{}'"),
    'branch_point_id': ('str', "'{}'"),
    'branch_worldline_id': ('str', "'{}'"),
    'parent_worldline_id': ('str', "'{}'"),
    'restore_barrier_id': ('str', '\'"counterfactual_selected_slice"\''),
    'cadence_reason': ('str', '\'"selected_slice_cadence_trace_runtime_window"\''),
    'mutation_dx': ('float', '0.0'),
    'mutation_dy': ('float', '0.0'),
    'mutation_dz': ('float', '0.0'),
    'mutation_dvx': ('float', '0.0'),
    'mutation_dvy': ('float', '0.0'),
    'mutation_dvz': ('float', '0.0'),
    'mutation_dheading': ('float', '0.0'),
    'allow_raw_authoritative_state_mutation': ('bool', 'False'),
    'evidence_refs': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
