"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('worldline_id', 'parent_worldline_id', 'deterministic_seed', 'world_index', 'entity_id', 'x', 'y', 'z', 'vx', 'vy', 'vz', 'heading', 'pitch', 'roll', 'snapshot_version', 'barrier_id', 'fidelity_profile_id', 'provider_family', 'selected_stage_node_id', 'cadence_reason', 'evidence_refs')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('worldline_id', 'parent_worldline_id', 'deterministic_seed', 'world_index', 'entity_id', 'x', 'y', 'z', 'vx', 'vy', 'vz', 'heading', 'pitch', 'roll', 'snapshot_version', 'barrier_id', 'fidelity_profile_id', 'provider_family', 'selected_stage_node_id', 'cadence_reason', 'evidence_refs')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'worldline_id': ('str', "'{}'"),
    'parent_worldline_id': ('str', "'{}'"),
    'deterministic_seed': ('object', "'0'"),
    'world_index': ('object', "'0'"),
    'entity_id': ('object', "'0'"),
    'x': ('float', '0.0'),
    'y': ('float', '0.0'),
    'z': ('float', '0.0'),
    'vx': ('float', '0.0'),
    'vy': ('float', '0.0'),
    'vz': ('float', '0.0'),
    'heading': ('float', '0.0'),
    'pitch': ('float', '0.0'),
    'roll': ('float', '0.0'),
    'snapshot_version': ('object', "'0'"),
    'barrier_id': ('str', '\'"counterfactual_selected_slice"\''),
    'fidelity_profile_id': ('str', "'{}'"),
    'provider_family': ('str', "'{}'"),
    'selected_stage_node_id': ('str', "'{}'"),
    'cadence_reason': ('str', "'{}'"),
    'evidence_refs': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
