"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('window_id', 'world_id', 'source_time_s', 'action_requests', 'observation_request', 'engagement_request', 'cadence_config', 'export_observation', 'export_engagement', 'export_diagnostics')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('window_id', 'world_id', 'source_time_s', 'action_requests', 'observation_request', 'engagement_request', 'cadence_config', 'export_observation', 'export_engagement', 'export_diagnostics')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'window_id': ('str', "'{}'"),
    'world_id': ('object', "'0'"),
    'source_time_s': ('float', '0.0'),
    'action_requests': ('object', "'{}'"),
    'observation_request': ('object', "'{}'"),
    'engagement_request': ('object', "'{}'"),
    'cadence_config': ('object', "'{}'"),
    'export_observation': ('bool', 'True'),
    'export_engagement': ('bool', 'True'),
    'export_diagnostics': ('bool', 'True'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
