"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('node_id', 'clock_domain', 'read_snapshot_policy', 'write_commit_policy', 'visible_input_count', 'execution_state', 'decision_reason', 'trigger_source', 'decision_barrier_id', 'clock_merge_policy', 'source_snapshot_version', 'source_time_s', 'target_window_id', 'barrier_order')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('node_id', 'clock_domain', 'read_snapshot_policy', 'write_commit_policy', 'visible_input_count', 'execution_state', 'decision_reason', 'trigger_source', 'decision_barrier_id', 'clock_merge_policy', 'source_snapshot_version', 'source_time_s', 'target_window_id', 'barrier_order')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'node_id': ('str', "'{}'"),
    'clock_domain': ('str', "'{}'"),
    'read_snapshot_policy': ('str', "'{}'"),
    'write_commit_policy': ('str', "'{}'"),
    'visible_input_count': ('object', "'0'"),
    'execution_state': ('str', '\'"skipped"\''),
    'decision_reason': ('str', "'{}'"),
    'trigger_source': ('str', "'{}'"),
    'decision_barrier_id': ('str', "'{}'"),
    'clock_merge_policy': ('str', "'{}'"),
    'source_snapshot_version': ('str', "'{}'"),
    'source_time_s': ('float', '0.0'),
    'target_window_id': ('str', "'{}'"),
    'barrier_order': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
