"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('world_index', 'seed', 'terrain_type', 'wind_speed_mps', 'wind_dir_from_deg', 'wind_shear_mps_per_km', 'maritime_configured', 'sea_state', 'wave_heading_deg', 'wave_period_s', 'zones', 'spawn_requests', 'time_steps')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('world_index', 'seed', 'terrain_type', 'wind_speed_mps', 'wind_dir_from_deg', 'wind_shear_mps_per_km', 'maritime_configured', 'sea_state', 'wave_heading_deg', 'wave_period_s', 'zones', 'spawn_requests', 'time_steps')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'world_index': ('object', "'0'"),
    'seed': ('object', "'42'"),
    'terrain_type': ('str', "'{}'"),
    'wind_speed_mps': ('float', '0.0'),
    'wind_dir_from_deg': ('float', '0.0'),
    'wind_shear_mps_per_km': ('float', '0.0'),
    'maritime_configured': ('bool', 'False'),
    'sea_state': ('float', '0.0'),
    'wave_heading_deg': ('float', '0.0'),
    'wave_period_s': ('float', '8.0'),
    'zones': ('object', "'{}'"),
    'spawn_requests': ('object', "'{}'"),
    'time_steps': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
