"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('supports_batch_runtime', 'supports_compiled_episode_controller', 'supports_compiled_execution_step', 'supports_gpu_visual', 'supports_gpu_observation', 'supports_gpu_flight_shaping', 'supports_device_observation_view', 'supports_resident_state', 'supports_exact_gpu_backend', 'supports_shadow_compare', 'maintained_baseline_backend_profile_id', 'maintained_baseline_parity_budget_ref', 'maintained_baseline_profile_status', 'device_observation_view_candidate_profile_id', 'device_observation_view_rejection_reason', 'exact_gpu_backend_candidate_profile_id', 'exact_gpu_backend_rejection_reason', 'resident_state_candidate_profile_id', 'resident_state_candidate_parity_budget_ref', 'resident_state_rejection_reason', 'shadow_compare_candidate_profile_id', 'shadow_compare_candidate_parity_budget_ref', 'shadow_compare_rejection_reason', 'multi_fidelity_rejection_reason')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('supports_batch_runtime', 'supports_compiled_episode_controller', 'supports_compiled_execution_step', 'supports_gpu_visual', 'supports_gpu_observation', 'supports_gpu_flight_shaping', 'supports_device_observation_view', 'supports_resident_state', 'supports_exact_gpu_backend', 'supports_shadow_compare', 'maintained_baseline_backend_profile_id', 'maintained_baseline_parity_budget_ref', 'maintained_baseline_profile_status', 'device_observation_view_candidate_profile_id', 'device_observation_view_rejection_reason', 'exact_gpu_backend_candidate_profile_id', 'exact_gpu_backend_rejection_reason', 'resident_state_candidate_profile_id', 'resident_state_candidate_parity_budget_ref', 'resident_state_rejection_reason', 'shadow_compare_candidate_profile_id', 'shadow_compare_candidate_parity_budget_ref', 'shadow_compare_rejection_reason', 'multi_fidelity_rejection_reason')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'supports_batch_runtime': ('bool', 'False'),
    'supports_compiled_episode_controller': ('bool', 'False'),
    'supports_compiled_execution_step': ('bool', 'False'),
    'supports_gpu_visual': ('bool', 'False'),
    'supports_gpu_observation': ('bool', 'False'),
    'supports_gpu_flight_shaping': ('bool', 'False'),
    'supports_device_observation_view': ('bool', 'False'),
    'supports_resident_state': ('bool', 'False'),
    'supports_exact_gpu_backend': ('bool', 'False'),
    'supports_shadow_compare': ('bool', 'False'),
    'maintained_baseline_backend_profile_id': ('str', "'{}'"),
    'maintained_baseline_parity_budget_ref': ('str', "'{}'"),
    'maintained_baseline_profile_status': ('str', "'{}'"),
    'device_observation_view_candidate_profile_id': ('str', "'{}'"),
    'device_observation_view_rejection_reason': ('str', "'{}'"),
    'exact_gpu_backend_candidate_profile_id': ('str', "'{}'"),
    'exact_gpu_backend_rejection_reason': ('str', "'{}'"),
    'resident_state_candidate_profile_id': ('str', "'{}'"),
    'resident_state_candidate_parity_budget_ref': ('str', "'{}'"),
    'resident_state_rejection_reason': ('str', "'{}'"),
    'shadow_compare_candidate_profile_id': ('str', "'{}'"),
    'shadow_compare_candidate_parity_budget_ref': ('str', "'{}'"),
    'shadow_compare_rejection_reason': ('str', "'{}'"),
    'multi_fidelity_rejection_reason': ('str', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
