"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'early_return', 'terminated', 'status_flag', 'reason_code', 'survival', 'crash_penalty', 'nan_guard_marker', 'stall_penalty', 'overload_penalty', 'failfast_penalty', 'gear_collapse_penalty', 'off_runway_penalty', 'gear_stress_penalty', 'off_runway_terminate_penalty')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'early_return', 'terminated', 'status_flag', 'reason_code', 'survival', 'crash_penalty', 'nan_guard_marker', 'stall_penalty', 'overload_penalty', 'failfast_penalty', 'gear_collapse_penalty', 'off_runway_penalty', 'gear_stress_penalty', 'off_runway_terminate_penalty'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'early_return': ('bool', 'False'),
    'terminated': ('bool', 'False'),
    'status_flag': ('float', '0.0'),
    'reason_code': ('object', "'TerminationReasonCode::Running'"),
    'survival': ('float', '0.0'),
    'crash_penalty': ('float', '0.0'),
    'nan_guard_marker': ('float', '0.0'),
    'stall_penalty': ('float', '0.0'),
    'overload_penalty': ('float', '0.0'),
    'failfast_penalty': ('float', '0.0'),
    'gear_collapse_penalty': ('float', '0.0'),
    'off_runway_penalty': ('float', '0.0'),
    'gear_stress_penalty': ('float', '0.0'),
    'off_runway_terminate_penalty': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
