"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('finite_state_valid', 'crash_penalty', 'survival_reward', 'health', 'airborne', 'aoa_valid', 'aoa_abs_deg', 'stall_threshold_deg', 'stall_penalty_weight', 'stall_penalty_clip', 'g_abs', 'overload_g_threshold', 'overload_penalty_weight', 'overload_penalty_clip', 'curr_alt_agl_m', 'overload_min_alt_agl_m', 'altitude_m', 'roll_abs_deg', 'pitch_abs_deg', 'failfast_penalty', 'gear_collapsed', 'gear_collapse_penalty', 'runway_surface_phase', 'on_runway_task', 'gear_stress', 'gear_stress_penalty_weight', 'off_runway_penalty', 'speed_mps', 'off_runway_steps', 'off_runway_terminate_speed', 'off_runway_terminate_grace_s', 'time_step_s', 'off_runway_terminate_penalty')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('finite_state_valid', 'crash_penalty', 'survival_reward', 'health', 'airborne', 'aoa_valid', 'aoa_abs_deg', 'stall_threshold_deg', 'stall_penalty_weight', 'stall_penalty_clip', 'g_abs', 'overload_g_threshold', 'overload_penalty_weight', 'overload_penalty_clip', 'curr_alt_agl_m', 'overload_min_alt_agl_m', 'altitude_m', 'roll_abs_deg', 'pitch_abs_deg', 'failfast_penalty', 'gear_collapsed', 'gear_collapse_penalty', 'runway_surface_phase', 'on_runway_task', 'gear_stress', 'gear_stress_penalty_weight', 'off_runway_penalty', 'speed_mps', 'off_runway_steps', 'off_runway_terminate_speed', 'off_runway_terminate_grace_s', 'time_step_s', 'off_runway_terminate_penalty')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'finite_state_valid': ('bool', 'True'),
    'crash_penalty': ('float', '-1000.0'),
    'survival_reward': ('float', '0.01'),
    'health': ('float', '100.0'),
    'airborne': ('bool', 'False'),
    'aoa_valid': ('bool', 'False'),
    'aoa_abs_deg': ('float', '0.0'),
    'stall_threshold_deg': ('float', '15.0'),
    'stall_penalty_weight': ('float', '-1.0'),
    'stall_penalty_clip': ('float', '0.0'),
    'g_abs': ('float', '1.0'),
    'overload_g_threshold': ('float', '6.0'),
    'overload_penalty_weight': ('float', '-1.0'),
    'overload_penalty_clip': ('float', '0.0'),
    'curr_alt_agl_m': ('float', '0.0'),
    'overload_min_alt_agl_m': ('float', '5.0'),
    'altitude_m': ('float', '0.0'),
    'roll_abs_deg': ('float', '0.0'),
    'pitch_abs_deg': ('float', '0.0'),
    'failfast_penalty': ('float', '-50.0'),
    'gear_collapsed': ('bool', 'False'),
    'gear_collapse_penalty': ('float', '-500.0'),
    'runway_surface_phase': ('bool', 'False'),
    'on_runway_task': ('bool', 'True'),
    'gear_stress': ('float', '0.0'),
    'gear_stress_penalty_weight': ('float', '-10.0'),
    'off_runway_penalty': ('float', '-1.0'),
    'speed_mps': ('float', '0.0'),
    'off_runway_steps': ('int', '0'),
    'off_runway_terminate_speed': ('float', '0.0'),
    'off_runway_terminate_grace_s': ('float', '0.0'),
    'time_step_s': ('float', '0.05'),
    'off_runway_terminate_penalty': ('float', '-200.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
