"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('request_id', 'request_version', 'contract_version', 'generation_kind', 'source', 'generator_version', 'has_deterministic_seed', 'deterministic_seed', 'baseline_scenario_ref', 'replay_envelope_ref', 'branch_point_ref', 'capability_refs', 'evidence_refs')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('request_id', 'request_version', 'contract_version', 'generation_kind', 'source', 'generator_version', 'has_deterministic_seed', 'deterministic_seed', 'baseline_scenario_ref', 'replay_envelope_ref', 'branch_point_ref', 'capability_refs', 'evidence_refs')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'request_id': ('str', '\'""\''),
    'request_version': ('str', '\'"1"\''),
    'contract_version': ('str', "'std::string(kScenarioGenerationContractVersionRequestV1)'"),
    'generation_kind': ('str', '\'""\''),
    'source': ('str', '\'""\''),
    'generator_version': ('str', '\'""\''),
    'has_deterministic_seed': ('bool', 'False'),
    'deterministic_seed': ('object', "'0'"),
    'baseline_scenario_ref': ('str', '\'""\''),
    'replay_envelope_ref': ('str', '\'""\''),
    'branch_point_ref': ('str', '\'""\''),
    'capability_refs': ('object', "'{}'"),
    'evidence_refs': ('object', "'{}'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
