"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('header', 'projected_hitbox_count', 'sample_count', 'hit_estimate', 'hit_fraction', 'energy_scale', 'pattern_scale', 'orientation_axis_forward', 'orientation_axis_right', 'orientation_axis_up')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('header', 'projected_hitbox_count', 'sample_count', 'hit_estimate', 'hit_fraction', 'energy_scale', 'pattern_scale', 'orientation_axis_forward', 'orientation_axis_right', 'orientation_axis_up')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'header': ('object', "'{}'"),
    'projected_hitbox_count': ('object', "'0'"),
    'sample_count': ('object', "'0'"),
    'hit_estimate': ('float', '0.0'),
    'hit_fraction': ('float', '0.0'),
    'energy_scale': ('float', '1.0'),
    'pattern_scale': ('float', '1.0'),
    'orientation_axis_forward': ('float', '0.0'),
    'orientation_axis_right': ('float', '0.0'),
    'orientation_axis_up': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
