"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'on_runway', 'gear_collapsed', 'gear_stress', 'on_ground', 'airborne', 'preliftoff', 'has_runway_frame', 'on_runway_geom', 'runway_cross_m', 'runway_along_m')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'on_runway', 'gear_collapsed', 'gear_stress', 'on_ground', 'airborne', 'preliftoff', 'has_runway_frame', 'on_runway_geom', 'runway_cross_m', 'runway_along_m'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'on_runway': ('bool', 'True'),
    'gear_collapsed': ('bool', 'False'),
    'gear_stress': ('float', '0.0'),
    'on_ground': ('bool', 'False'),
    'airborne': ('bool', 'False'),
    'preliftoff': ('bool', 'True'),
    'has_runway_frame': ('bool', 'False'),
    'on_runway_geom': ('bool', 'False'),
    'runway_cross_m': ('float', '0.0'),
    'runway_along_m': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
