"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('formation_template_id', 'formation_contract_id', 'formation_role_id', 'wingman_slot_id', 'join_policy_id', 'rejoin_policy_id', 'mutual_support_mode', 'support_sector_id')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('formation_template_id', 'formation_contract_id', 'formation_role_id', 'wingman_slot_id', 'join_policy_id', 'rejoin_policy_id', 'mutual_support_mode', 'support_sector_id')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'formation_template_id': ('object', "'0'"),
    'formation_contract_id': ('object', "'0'"),
    'formation_role_id': ('object', "'FormationRole::Unspecified'"),
    'wingman_slot_id': ('object', "'WingmanSlot::Unspecified'"),
    'join_policy_id': ('int', '0'),
    'rejoin_policy_id': ('int', '0'),
    'mutual_support_mode': ('int', '0'),
    'support_sector_id': ('object', "'0'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
