"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('anchor_x_m', 'anchor_y_m', 'anchor_z_m', 'station_type', 'station_radius_m', 'station_leg_length_m', 'station_heading_deg', 'altitude_block_min_m', 'altitude_block_max_m', 'target_altitude_m', 'speed_min_mps', 'speed_max_mps', 'target_speed_mps', 'entry_condition_code', 'exit_condition_code', 'on_station_time_s', 'fuel_bingo_override_kg')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('anchor_x_m', 'anchor_y_m', 'anchor_z_m', 'station_type', 'station_radius_m', 'station_leg_length_m', 'station_heading_deg', 'altitude_block_min_m', 'altitude_block_max_m', 'target_altitude_m', 'speed_min_mps', 'speed_max_mps', 'target_speed_mps', 'entry_condition_code', 'exit_condition_code', 'on_station_time_s', 'fuel_bingo_override_kg')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'anchor_x_m': ('float', '0.0'),
    'anchor_y_m': ('float', '0.0'),
    'anchor_z_m': ('float', '0.0'),
    'station_type': ('object', "'StationType::Orbit'"),
    'station_radius_m': ('float', '0.0'),
    'station_leg_length_m': ('float', '0.0'),
    'station_heading_deg': ('float', '0.0'),
    'altitude_block_min_m': ('float', '0.0'),
    'altitude_block_max_m': ('float', '0.0'),
    'target_altitude_m': ('float', '0.0'),
    'speed_min_mps': ('float', '0.0'),
    'speed_max_mps': ('float', '0.0'),
    'target_speed_mps': ('float', '0.0'),
    'entry_condition_code': ('int', '0'),
    'exit_condition_code': ('int', '0'),
    'on_station_time_s': ('float', '0.0'),
    'fuel_bingo_override_kg': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
