"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('track_id', 'correlated_entity', 'has_correlated_entity', 'correlation_policy', 'source', 'classification', 'status', 'quality', 'confidence', 'usable', 'iff', 'source_time_s', 'update_age_s', 'snapshot_version')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('track_id', 'correlated_entity', 'has_correlated_entity', 'correlation_policy', 'source', 'classification', 'status', 'quality', 'confidence', 'usable', 'iff', 'source_time_s', 'update_age_s', 'snapshot_version')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'track_id': ('object', "'0'"),
    'correlated_entity': ('object', "'{}'"),
    'has_correlated_entity': ('bool', 'False'),
    'correlation_policy': ('str', '\'"unresolved"\''),
    'source': ('str', "'{}'"),
    'classification': ('str', '\'"unknown"\''),
    'status': ('str', '\'"unknown"\''),
    'quality': ('float', '0.0'),
    'confidence': ('float', '0.0'),
    'usable': ('bool', 'False'),
    'iff': ('str', '\'"unknown"\''),
    'source_time_s': ('float', '0.0'),
    'update_age_s': ('float', '0.0'),
    'snapshot_version': ('object', "'0'"),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
