"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'waypoint_index', 'waypoint_count', 'is_flyover', 'has_guidance', 'passed_fix', 'dist_m', 'xtk_m', 'dtg_m', 'waypoint_radius_m', 'leg_len_m', 'lead_turn_m', 'sequence_gate_m', 'has_prev_dist', 'prev_dist_m', 'route_length_m', 'turn_relief_activation', 'progress_weight', 'progress_negative_scale', 'distance_weight', 'distance_clip_m', 'distance_scale_by_route', 'distance_route_ref_m', 'distance_route_scale_min', 'distance_route_scale_max', 'cross_track_weight', 'cross_track_deadband_m', 'cross_track_norm_m', 'cross_track_power', 'cross_track_clip', 'turn_relief_max', 'proximity_weight', 'proximity_ref_m', 'proximity_power', 'reached_bonus')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('valid', 'waypoint_index', 'waypoint_count', 'is_flyover', 'has_guidance', 'passed_fix', 'dist_m', 'xtk_m', 'dtg_m', 'waypoint_radius_m', 'leg_len_m', 'lead_turn_m', 'sequence_gate_m', 'has_prev_dist', 'prev_dist_m', 'route_length_m', 'turn_relief_activation', 'progress_weight', 'progress_negative_scale', 'distance_weight', 'distance_clip_m', 'distance_scale_by_route', 'distance_route_ref_m', 'distance_route_scale_min', 'distance_route_scale_max', 'cross_track_weight', 'cross_track_deadband_m', 'cross_track_norm_m', 'cross_track_power', 'cross_track_clip', 'turn_relief_max', 'proximity_weight', 'proximity_ref_m', 'proximity_power', 'reached_bonus')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'waypoint_index': ('int', '0'),
    'waypoint_count': ('int', '0'),
    'is_flyover': ('bool', 'False'),
    'has_guidance': ('bool', 'False'),
    'passed_fix': ('bool', 'False'),
    'dist_m': ('float', '0.0'),
    'xtk_m': ('float', '0.0'),
    'dtg_m': ('float', '0.0'),
    'waypoint_radius_m': ('float', '500.0'),
    'leg_len_m': ('float', '0.0'),
    'lead_turn_m': ('float', '0.0'),
    'sequence_gate_m': ('float', '500.0'),
    'has_prev_dist': ('bool', 'False'),
    'prev_dist_m': ('float', '0.0'),
    'route_length_m': ('float', '0.0'),
    'turn_relief_activation': ('float', '0.0'),
    'progress_weight': ('float', '0.0'),
    'progress_negative_scale': ('float', '1.0'),
    'distance_weight': ('float', '0.0'),
    'distance_clip_m': ('float', '0.0'),
    'distance_scale_by_route': ('bool', 'False'),
    'distance_route_ref_m': ('float', '55000.0'),
    'distance_route_scale_min': ('float', '0.5'),
    'distance_route_scale_max': ('float', '1.0'),
    'cross_track_weight': ('float', '0.0'),
    'cross_track_deadband_m': ('float', '0.0'),
    'cross_track_norm_m': ('float', '1000.0'),
    'cross_track_power': ('float', '1.0'),
    'cross_track_clip': ('float', '0.0'),
    'turn_relief_max': ('float', '0.0'),
    'proximity_weight': ('float', '0.0'),
    'proximity_ref_m': ('float', '0.0'),
    'proximity_power': ('float', '1.0'),
    'reached_bonus': ('float', '0.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
