"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('valid', 'waypoint_progress', 'waypoint_distance', 'waypoint_cross_track', 'waypoint_proximity', 'waypoint_reached_bonus', 'arrived', 'next_prev_dist_valid', 'next_prev_dist_m')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ()

READONLY_FIELDS: frozenset[str] = frozenset(('valid', 'waypoint_progress', 'waypoint_distance', 'waypoint_cross_track', 'waypoint_proximity', 'waypoint_reached_bonus', 'arrived', 'next_prev_dist_valid', 'next_prev_dist_m'))

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'valid': ('bool', 'False'),
    'waypoint_progress': ('float', '0.0'),
    'waypoint_distance': ('float', '0.0'),
    'waypoint_cross_track': ('float', '0.0'),
    'waypoint_proximity': ('float', '0.0'),
    'waypoint_reached_bonus': ('float', '0.0'),
    'arrived': ('bool', 'False'),
    'next_prev_dist_valid': ('bool', 'False'),
    'next_prev_dist_m': ('float', '0.0'),
}

# All fields are read-only products exposed through def_ro bindings; no
# assigner is generated. Read values directly from the DTO attributes.
