"""GENERATED by tools/maintenance/dto_schema — edit the schema, not this file."""
# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.

from __future__ import annotations


FIELD_NAMES: tuple[str, ...] = ('world_index', 'side', 'type_name', 'entity_name', 'is_agent', 'x', 'y', 'z', 'heading', 'pitch', 'roll', 'vx', 'vy', 'vz', 'ammo_override_enabled', 'missiles_remaining', 'max_missiles', 'weapon_cooldown_override_enabled', 'weapon_cooldown_s', 'weapon_last_fire_time')

WRITABLE_FIELD_NAMES: tuple[str, ...] = ('world_index', 'side', 'type_name', 'entity_name', 'is_agent', 'x', 'y', 'z', 'heading', 'pitch', 'roll', 'vx', 'vy', 'vz', 'ammo_override_enabled', 'missiles_remaining', 'max_missiles', 'weapon_cooldown_override_enabled', 'weapon_cooldown_s', 'weapon_last_fire_time')

READONLY_FIELDS: frozenset[str] = frozenset()

FIELD_DEFAULTS: dict[str, tuple[str, str]] = {
    'world_index': ('object', "'0'"),
    'side': ('object', "'Side::Neutral'"),
    'type_name': ('str', "'{}'"),
    'entity_name': ('str', "'{}'"),
    'is_agent': ('bool', 'False'),
    'x': ('float', '0.0'),
    'y': ('float', '0.0'),
    'z': ('float', '0.0'),
    'heading': ('float', '0.0'),
    'pitch': ('float', '0.0'),
    'roll': ('float', '0.0'),
    'vx': ('float', '0.0'),
    'vy': ('float', '0.0'),
    'vz': ('float', '0.0'),
    'ammo_override_enabled': ('bool', 'False'),
    'missiles_remaining': ('int', '0'),
    'max_missiles': ('int', '0'),
    'weapon_cooldown_override_enabled': ('bool', 'False'),
    'weapon_cooldown_s': ('float', '2.0'),
    'weapon_last_fire_time': ('float', '-1.0'),
}

_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
