"""Declarative DTO schema model used by the X-macro generator."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
import re


DEFAULT_FILE_HEADER = (
  "// GENERATED by tools/maintenance/dto_schema — "
  "edit the schema, not this file.\n\n"
)

_CPP_IDENTIFIER = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
_MACRO_IDENTIFIER = re.compile(r"[A-Z_][A-Z0-9_]*\Z")


@dataclass(frozen=True, slots=True)
class Field:
  """One generated C++ field and future binding/serialization metadata."""

  name: str
  cpp_type: str
  default: str
  group: str
  comment: str | None = None
  python_name: str | None = None
  readonly: bool = False
  hidden: bool = False
  json_key: str | None = None

  def __post_init__(self) -> None:
    if _CPP_IDENTIFIER.fullmatch(self.name) is None:
      raise ValueError(f"invalid C++ field name: {self.name!r}")
    if not self.cpp_type or "\n" in self.cpp_type:
      raise ValueError(f"invalid C++ type for {self.name}: {self.cpp_type!r}")
    if not self.default or "\n" in self.default:
      raise ValueError(f"invalid default for {self.name}: {self.default!r}")
    if _MACRO_IDENTIFIER.fullmatch(self.group) is None:
      raise ValueError(f"invalid X-macro group for {self.name}: {self.group!r}")
    if self.comment is not None and "\n" in self.comment:
      raise ValueError(f"field comments must be single-line: {self.name}")


@dataclass(frozen=True, slots=True)
class DtoSchema:
  """One DTO-family schema and its checked-in generated artifact."""

  name: str
  output_path: str
  fields: tuple[Field, ...]
  file_header: str = DEFAULT_FILE_HEADER
  file_footer: str = ""

  def __post_init__(self) -> None:
    if "\r" in self.file_header or "\r" in self.file_footer:
      raise ValueError(f"DTO schema {self.name!r} templates must use LF line endings")
    output_path = PurePosixPath(self.output_path)
    if output_path.is_absolute() or ".." in output_path.parts:
      raise ValueError(f"output path must be repository-relative: {self.output_path}")
    if output_path.suffix != ".inc":
      raise ValueError(f"DTO schema output must be an .inc file: {self.output_path}")
    if not self.fields:
      raise ValueError(f"DTO schema {self.name!r} has no fields")

    names = [field.name for field in self.fields]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
      raise ValueError(f"duplicate fields in {self.name}: {duplicates}")
