"""Render checked-in Python builder modules from DTO schemas.

This is a rendering library consumed by generate.py; it has no CLI. Builder
modules live under gym_envs/scenario_loader/_generated/ and are covered by
generate.py --check together with the C++ .inc fragments.

Rendering rules:
- Every builder exports FIELD_NAMES, WRITABLE_FIELD_NAMES, READONLY_FIELDS,
  and FIELD_DEFAULTS.
- assign_from_object() is only generated when the schema has at least one
  writable field, and it always skips READONLY_FIELDS (even when they are
  explicitly listed in the fields argument), so it can never attempt to set
  a read-only def_ro binding property.
- Schemas whose fields are all read-only (products DTOs) get no assigner:
  reading happens directly through DTO attributes, and no current consumer
  needs a dict-export helper.
"""

from __future__ import annotations

from tools.maintenance.dto_schema.model import DtoSchema


GENERATED_PACKAGE_DIR = "gym_envs/scenario_loader/_generated"
PACKAGE_INIT_PATH = f"{GENERATED_PACKAGE_DIR}/__init__.py"

_PACKAGE_INIT_TEXT = (
  '"""GENERATED DTO builder package \u2014 do not edit files in this directory."""\n'
  "# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.\n"
)

_FILE_HEADER = (
  '"""GENERATED by tools/maintenance/dto_schema \u2014 edit the schema, not this file."""\n'
  "# Freshness is enforced by tools/maintenance/dto_schema/generate.py --check.\n"
  "\n"
  "from __future__ import annotations\n"
  "\n"
  "\n"
)

_ASSIGNER_TEMPLATE = '''\
_SENTINEL = object()


def assign_from_object(
    dto: object,
    source: object,
    fields: tuple[str, ...] | None = None,
) -> int:
    """Copy same-name writable attributes from source onto dto.

    Read-only fields are always skipped, even when explicitly listed in
    fields, so this can never attempt to set a read-only binding property.
    Only fields present on source are assigned. Returns the assigned count.
    """
    target_fields = WRITABLE_FIELD_NAMES if fields is None else fields
    count = 0
    for name in target_fields:
        if name in READONLY_FIELDS:
            continue
        val = getattr(source, name, _SENTINEL)
        if val is not _SENTINEL:
            setattr(dto, name, val)
            count += 1
    return count
'''

_READONLY_FOOTNOTE = (
  "# All fields are read-only products exposed through def_ro bindings; no\n"
  "# assigner is generated. Read values directly from the DTO attributes.\n"
)

_CPP_TO_PY_TYPE = {
  "bool": "bool",
  "int": "int",
  "double": "float",
  "float": "float",
  "std::string": "str",
}


def builder_output_path(schema: DtoSchema) -> str:
  return f"{GENERATED_PACKAGE_DIR}/{schema.name}_builder.py"


def _python_type(cpp_type: str) -> str:
  return _CPP_TO_PY_TYPE.get(cpp_type, "object")


def _python_default_repr(cpp_type: str, default: str) -> str:
  py_type = _python_type(cpp_type)
  if py_type == "bool":
    return "True" if default == "true" else "False"
  if py_type in {"int", "float"}:
    return default
  return repr(default)


def render_builder_text(schema: DtoSchema) -> str:
  field_names = tuple(field.name for field in schema.fields)
  writable_names = tuple(field.name for field in schema.fields if not field.readonly)
  readonly_names = tuple(field.name for field in schema.fields if field.readonly)

  parts = [_FILE_HEADER]
  parts.append(f"FIELD_NAMES: tuple[str, ...] = {field_names!r}\n\n")
  parts.append(f"WRITABLE_FIELD_NAMES: tuple[str, ...] = {writable_names!r}\n\n")
  if readonly_names:
    parts.append(
      f"READONLY_FIELDS: frozenset[str] = frozenset({readonly_names!r})\n\n"
    )
  else:
    parts.append("READONLY_FIELDS: frozenset[str] = frozenset()\n\n")
  parts.append("FIELD_DEFAULTS: dict[str, tuple[str, str]] = {\n")
  for field in schema.fields:
    py_type = _python_type(field.cpp_type)
    default_repr = _python_default_repr(field.cpp_type, field.default)
    parts.append(f"    {field.name!r}: ({py_type!r}, {default_repr!r}),\n")
  parts.append("}\n\n")
  if writable_names:
    parts.append(_ASSIGNER_TEMPLATE)
  else:
    parts.append(_READONLY_FOOTNOTE)
  return "".join(parts)


def _encode(text: str, line_ending: str) -> bytes:
  if line_ending not in {"\n", "\r\n"}:
    raise ValueError(f"unsupported line ending: {line_ending!r}")
  if line_ending != "\n":
    text = text.replace("\n", line_ending)
  return text.encode("utf-8")


def render_builder_bytes(schema: DtoSchema, line_ending: str = "\n") -> bytes:
  return _encode(render_builder_text(schema), line_ending)


def render_package_init_bytes(line_ending: str = "\n") -> bytes:
  return _encode(_PACKAGE_INIT_TEXT, line_ending)
