from __future__ import annotations

from python.scenario.compiler import (
    DEFAULT_TERRAIN_TYPE,
    REPO_ROOT,
    TERRAIN_TYPE_SOURCE_COMPATIBILITY,
    TERRAIN_TYPE_SOURCE_DEFAULT,
    TERRAIN_TYPE_SOURCE_EXPLICIT,
    _SCALAR_TYPES,
    _OBJECTIVE_PROPERTY_MAP,
    _OBJECTIVE_OP_MAP,
    _OBJECTIVE_DYNAMIC_TARGET_MAP,
    _SURFACE_TYPE_MAP,
    _mtime_ns,
    _clone_scenario_value,
    _coerce_nonnegative_int,
    _normalize_terrain_type_value,
    _normalize_waypoint_mode,
    _resolve_environment_terrain_type,
    _terrain_type_source_for_value,
    _canonical_recovery_approach_name,
    _stable_ref_id,
    resolve_environment_terrain_config,
    _merge_prefab_data,
    _compile_merged_scenario_data,
    _clone_runtime_environment,
    _clone_runtime_entity,
    _clone_runtime_entities,
    _clone_runtime_mission_command,
    _clone_runtime_task_order,
    _clone_runtime_cooperative_roster,
    _clone_runtime_environment_context,
    _extract_runtime_agent_spawn_context,
    _clone_runtime_scenario_data,
    _clone_runtime_context_scenario_data,
    _normalize_runtime_mission_command,
    _normalize_runtime_waypoints,
    _resolve_route_ref_id,
    invalidate_runtime_waypoint_cache,
    cache_runtime_waypoint_cache,
    materialize_runtime_waypoint_cache,
    _compile_normalized_waypoint_templates,
    _compile_waypoint_template_route_ref_ids,
    _extract_ils_beacons,
    rotate_ils_beacon_templates,
    _primary_runway_heading_deg,
    _infer_wind_ref_alt_m,
    _compile_world_layout_template,
    _compile_conditional_objectives,
    _build_objective_shaping_config,
    WaypointModeRewardConfig,
    ApproachRewardConfig,
    SafetyRewardConfig,
    LNavRuntimeConfig,
    CompiledZoneLayoutTemplate,
    CompiledSpawnLayoutTemplate,
    CompiledWorldLayoutTemplate,
    CompiledScenarioRuntimeMetadata,
    _cfg_value_for_waypoint_mode,
    _build_waypoint_mode_reward_config,
    _build_approach_reward_config,
    _build_safety_reward_config,
    _build_lnav_runtime_config,
    CompiledScenario,
    ScenarioCompiler,
)
from python.scenario.compiler import __all__ as _SCENARIO_COMPILER_ALL


__all__ = list(_SCENARIO_COMPILER_ALL)
