from __future__ import annotations

CONTRACT_SCHEMA_VERSION = 1
DIAGNOSTIC_ROW_SCHEMA_VERSION = 9

STAGE_NEAREST_APPROACH = "nearest_approach"
STAGE_FUZE = "fuze"
STAGE_WARHEAD_MECHANISM = "warhead_mechanism"
STAGE_SPATIAL_COVERAGE = "spatial_coverage"
STAGE_COMPONENT_LOAD = "component_load"
STAGE_COMPONENT_DAMAGE = "component_damage"
STAGE_STRUCTURAL_BREAKUP = "structural_breakup"
STAGE_PLATFORM_CONSEQUENCE = "platform_consequence"
STAGE_LIFECYCLE = "lifecycle"
STAGE_TRAINING_PROJECTION = "training_projection"

CANONICAL_STAGES = (
    STAGE_NEAREST_APPROACH,
    STAGE_FUZE,
    STAGE_WARHEAD_MECHANISM,
    STAGE_SPATIAL_COVERAGE,
    STAGE_COMPONENT_LOAD,
    STAGE_COMPONENT_DAMAGE,
    STAGE_STRUCTURAL_BREAKUP,
    STAGE_PLATFORM_CONSEQUENCE,
    STAGE_LIFECYCLE,
    STAGE_TRAINING_PROJECTION,
)

DIAGNOSTIC_ROW_STAGES = (
    STAGE_NEAREST_APPROACH,
    STAGE_FUZE,
    STAGE_WARHEAD_MECHANISM,
    STAGE_SPATIAL_COVERAGE,
    STAGE_COMPONENT_LOAD,
    STAGE_COMPONENT_DAMAGE,
    STAGE_STRUCTURAL_BREAKUP,
    STAGE_PLATFORM_CONSEQUENCE,
    STAGE_LIFECYCLE,
)

EFFECTIVE_DETONATION_STAGES = frozenset(
    {
        STAGE_WARHEAD_MECHANISM,
        STAGE_SPATIAL_COVERAGE,
        STAGE_COMPONENT_LOAD,
        STAGE_COMPONENT_DAMAGE,
    }
)

REASON_FUZE_ARMED = "fuze_armed"
REASON_FUZE_NO_DETONATION = "fuze_no_detonation"
REASON_FUZE_NO_TERMINAL_TRACK = "fuze_no_terminal_track"
REASON_MISS_OUTSIDE_TRIGGER_RADIUS = "miss_outside_trigger_radius"
REASON_OUTSIDE_SENSOR_WINDOW = "outside_sensor_window"
REASON_TARGET_NOT_DETECTED = "target_not_detected"
REASON_MISSILE_TIMEOUT = "missile_timeout"
REASON_PLATFORM_CONSEQUENCE_PROJECTION = "generic_research_platform_consequence_projection"
REASON_LIFECYCLE_PROJECTION = "transitional_damage_report_projection"

TERMINAL_NEGATIVE_REASONS = frozenset(
    {
        REASON_FUZE_NO_DETONATION,
        REASON_FUZE_NO_TERMINAL_TRACK,
        REASON_MISS_OUTSIDE_TRIGGER_RADIUS,
        REASON_OUTSIDE_SENSOR_WINDOW,
        REASON_TARGET_NOT_DETECTED,
        REASON_MISSILE_TIMEOUT,
    }
)

OBSERVATION_MODE_SAMPLED_RUNTIME = "sampled_runtime"
OBSERVATION_MODE_EXPECTED_PROJECTION = "expected_projection"

CONSUMER_VISIBILITY_DIAGNOSTICS_AND_TRAINING = "diagnostics_and_training"
CONSUMER_VISIBILITY_DIAGNOSTICS_ONLY = "diagnostics_only"
