if (NOT DEFINED MANIFEST OR NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "runtime authority boundary manifest is missing: ${MANIFEST}")
endif()
file(READ "${MANIFEST}" manifest_text)
string(REPLACE "\r\n" "\n" manifest_text "${manifest_text}")
foreach(field IN ITEMS type links interface_links includes interface_includes sources)
    string(REGEX MATCH "(^|\n)${field}=([^\n]*)" field_match "${manifest_text}")
    if (NOT field_match)
        message(FATAL_ERROR "runtime authority manifest field is missing: ${field}")
    endif()
    set(${field} "${CMAKE_MATCH_2}")
endforeach()
if (NOT type STREQUAL "STATIC_LIBRARY")
    message(FATAL_ERROR "authority contract target is not static: ${type}")
endif()
foreach(forbidden IN ITEMS ef_core ef_facade flecs nanobind Cordis)
    string(FIND "${links}|${interface_links}|${sources}" "${forbidden}" position)
    if (NOT position EQUAL -1)
        message(FATAL_ERROR "authority contract target contains forbidden dependency: ${forbidden}")
    endif()
endforeach()
