if (NOT DEFINED MANIFEST OR NOT EXISTS "${MANIFEST}")
    message(FATAL_ERROR "runtime run recorder manifest is missing: ${MANIFEST}")
endif()
file(READ "${MANIFEST}" manifest_text)
string(REPLACE "\r\n" "\n" manifest_text "${manifest_text}")
foreach(field IN ITEMS type links interface_links includes interface_includes sources)
    string(REGEX MATCH "(^|\n)${field}=([^\n]*)" field_match "${manifest_text}")
    if (NOT field_match)
        message(FATAL_ERROR "runtime run recorder manifest field is missing: ${field}")
    endif()
    set(${field}_value "${CMAKE_MATCH_2}")
endforeach()
if (NOT type_value STREQUAL "STATIC_LIBRARY")
    message(FATAL_ERROR "ef_runtime_run_recorder is not static: ${type_value}")
endif()
if (NOT links_value MATCHES "ef_runtime_authority_contracts" OR
    NOT links_value MATCHES "nlohmann_json")
    message(FATAL_ERROR "recorder must link authority canonical/digest and JSON dependencies: ${links_value}")
endif()
foreach(forbidden IN ITEMS ef_core ef_facade ef_py ef_cuda_resident_backend flecs nanobind Cordis SimulationKernel WorldBatchRuntime RuntimeFacade)
    string(FIND "${links_value}|${interface_links_value}|${sources_value}" "${forbidden}" position)
    if (NOT position EQUAL -1)
        message(FATAL_ERROR "recorder contains forbidden engine/binding dependency: ${forbidden}")
    endif()
endforeach()
if (interface_links_value MATCHES "ef_core|ef_facade|ef_py|flecs|nanobind")
    message(FATAL_ERROR "recorder interface exposes forbidden dependencies: ${interface_links_value}")
endif()
